import ornament from './data/ornament.json';
import {TestPage,originalPageHeight,originalPageWidth} from './model';
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export type PageFonts={page:string;title:string;basmala:string};
/** True QPC glyphs and COLR palettes; no OCR, rasterisation or substitute text. */
export function testPageHtml(page:TestPage,fonts:PageFonts){
 const lines=page.lines.map((line,index)=>{const basmalaSurah=page.lines.slice(index+1).find(next=>next.words.length)?.words[0][1]??page.surah;return `<div class="line ${line.centered?'centered':''}" data-line="${line.line}">${line.type==='ayah'?line.words.map(w=>`<span class="word" data-id="${w[0]}" data-verse="${w[1]}:${w[2]}" aria-label="${escape(w[5])}">${escape(w[4])}</span>`).join(''):line.type==='surah_name'?`<div class="surah-heading">${ornament}<span class="surah">surah${String(line.surah).padStart(3,'0')}</span></div>`:`<span class="basmala">${basmalaSurah===2?'ﲚﲛﲞﲤ':basmalaSurah===95||basmalaSurah===97?'ﭗﲫﲮﲴ':'ﲪﲫﲮﲴ'}</span>`}</div>`;}).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src data: http://127.0.0.1:*; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>
@font-face{font-family:Page;src:url('${fonts.page}') format('woff2')}@font-face{font-family:Title;src:url('${fonts.title}') format('woff2')}@font-face{font-family:Basmala;src:url('${fonts.basmala}') format('woff2')}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#faf7f2;touch-action:none;user-select:none;-webkit-user-select:none}
#paper{width:${originalPageWidth}px;height:${originalPageHeight}px;position:absolute;visibility:hidden;transform-origin:top left;padding:70px 30px 55px;color:#111;background:#faf7f2}
.top{height:105px;display:flex;align-items:center;justify-content:space-between;font:30px sans-serif;color:#795e50}.top .surah{font:68px Title}
.body{height:1830px;display:flex;flex-direction:column;justify-content:center}.line{height:122px;flex-shrink:0;display:flex;direction:rtl;align-items:center;justify-content:space-between;font:${page.fontSize}px Page;white-space:nowrap;line-height:1}.line.centered{justify-content:center;gap:8px}.word{display:inline-block;direction:rtl}.surah-heading{position:relative;width:100%;height:100px;display:flex;justify-content:center;align-items:center}.surah-heading svg{position:absolute;width:100%;height:100%;inset:0}.line .surah{position:relative;font:90px Title}.basmala{font:80px Basmala}footer{text-align:center;font:30px sans-serif;margin-top:20px}
#verse-overlay{position:absolute;inset:0;pointer-events:none;visibility:hidden}
</style></head><body><main id="paper" aria-label="Coran avec règles de Tajwid, page ${page.page}"><div class="top"><span>Juz ${page.juz}</span><span class="surah">surah${String(page.surah).padStart(3,'0')}</span></div><div class="body">${lines}</div><footer>${String(page.page).replace(/\d/g,c=>'٠١٢٣٤٥٦٧٨٩'[Number(c)])}</footer><div id="verse-overlay" aria-hidden="true"></div></main><script>
const paper=document.getElementById('paper'),overlay=document.getElementById('verse-overlay');let scale=1;let readerState={enabled:false},regions={},hold=null,gesture=null;
const send=data=>{if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify(data));else window.parent.postMessage(data,'*')};
function fit(){scale=Math.min(innerWidth/${originalPageWidth},innerHeight/${originalPageHeight});paper.style.transform='scale('+scale+')';paper.style.left=((innerWidth-${originalPageWidth}*scale)/2)+'px';paper.style.top='0px';}
function drawOverlay(){overlay.replaceChildren();overlay.style.visibility=readerState.enabled?'visible':'hidden';if(!readerState.enabled)return;for(const [key,zones] of Object.entries(regions)){const active=key===readerState.playing,bookmarked=readerState.bookmarks.includes(key),difficult=readerState.difficulty.includes(key),selected=key===readerState.selected,inSession=readerState.session.includes(key);if(!active&&!bookmarked&&!difficult&&!selected&&!inSession)continue;for(const zone of zones){const mark=document.createElement('div');Object.assign(mark.style,{position:'absolute',left:zone.x*100+'%',top:zone.y*100+'%',width:zone.width*100+'%',height:zone.height*100+'%',borderRadius:'7px',backgroundColor:active||selected?readerState.selection:bookmarked?readerState.primary:difficult?'#E85B5B':readerState.gold,opacity:active||selected?'0.38':'0.16',border:'none'});overlay.appendChild(mark);}if(bookmarked&&zones[0]){const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 24 24');Object.assign(icon.style,{position:'absolute',right:'0',top:zones[0].y*100+'%',width:'23px',height:'23px',color:readerState.primary});const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M6 3h12v18l-6-4-6 4z');path.setAttribute('fill','currentColor');icon.appendChild(path);overlay.appendChild(icon);}}}
window.applyReaderState=state=>{readerState=state;drawOverlay();};addEventListener('message',event=>{if(event.source===window.parent&&event.data?.type==='reader-state')window.applyReaderState(event.data.state);});
function ready(){fit();paper.style.visibility='visible';const p=paper.getBoundingClientRect();const words=[...document.querySelectorAll('.word')].map(w=>{const b=w.getBoundingClientRect();return {id:Number(w.dataset.id),key:w.dataset.verse,region:{x:(b.left-p.left)/p.width,y:(b.top-p.top)/p.height,width:b.width/p.width,height:b.height/p.height,line:Number(w.parentElement.dataset.line)}}});regions={};for(const word of words){const zones=regions[word.key]||(regions[word.key]=[]),r=word.region,same=zones.find(z=>z.line===r.line);if(same){const right=Math.max(same.x+same.width,r.x+r.width),bottom=Math.max(same.y+same.height,r.y+r.height);same.x=Math.min(same.x,r.x);same.y=Math.min(same.y,r.y);same.width=right-same.x;same.height=bottom-same.y;}else zones.push({...r});}drawOverlay();send({type:'ready',page:${page.page},words});}
addEventListener('resize',ready);document.fonts.ready.then(ready).catch(()=>send({type:'error',page:${page.page}}));
function hit(x,y){const p=paper.getBoundingClientRect(),nx=(x-p.left)/p.width,ny=(y-p.top)/p.height;for(const [key,zones] of Object.entries(regions))if(zones.some(r=>nx>=r.x&&nx<=r.x+r.width&&ny>=r.y&&ny<=r.y+r.height))return key;return null;}
function cancelHold(){if(hold!==null)clearTimeout(hold);hold=null;}
function begin(x,y){cancelHold();gesture={x,y,key:hit(x,y),held:false,moved:false};if(readerState.enabled)hold=setTimeout(()=>{if(gesture&&!gesture.moved){gesture.held=true;send({type:'longpress',key:gesture.key});}},450);}
function move(x,y){if(gesture&&Math.hypot(x-gesture.x,y-gesture.y)>10){gesture.moved=true;cancelHold();}}
function end(x,y){cancelHold();if(!gesture)return;const g=gesture,dx=x-g.x,dy=y-g.y;gesture=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)send({type:'swipe',dx,dy,fromEdge:g.x<20});else if(readerState.enabled&&!g.held&&!g.moved)send({type:'tap',key:g.key});}
addEventListener('touchstart',e=>{const t=e.changedTouches[0];begin(t.clientX,t.clientY);},{passive:true});addEventListener('touchmove',e=>{const t=e.changedTouches[0];move(t.clientX,t.clientY);},{passive:true});addEventListener('touchend',e=>{const t=e.changedTouches[0];end(t.clientX,t.clientY);},{passive:true});addEventListener('touchcancel',()=>{cancelHold();gesture=null;},{passive:true});
addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')begin(e.clientX,e.clientY)});addEventListener('pointermove',e=>{if(e.pointerType==='mouse')move(e.clientX,e.clientY)});addEventListener('pointerup',e=>{if(e.pointerType==='mouse')end(e.clientX,e.clientY)});addEventListener('contextmenu',e=>e.preventDefault());
</script></body></html>`;
}
