const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function setup(fail=false,platform='ios'){
 const legacy=new Map(),secure=new Map();const asyncStorage={getItem:async k=>legacy.get(k)??null,setItem:async(k,v)=>legacy.set(k,v),removeItem:async k=>legacy.delete(k)};
 const secureStore={AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY:4,getItemAsync:async k=>secure.get(k)??null,setItemAsync:async(k,v)=>{if(fail)throw Error('Keychain unavailable');secure.set(k,v);},deleteItemAsync:async k=>secure.delete(k)};
 const code=ts.transpileModule(fs.readFileSync('src/services/authStorage.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 const module={exports:{}};vm.runInNewContext(code,{exports:module.exports,require:n=>n.includes('async-storage')?{__esModule:true,default:asyncStorage}:n==='expo-secure-store'?secureStore:{Platform:{OS:platform}},Date,Math,JSON});return {storage:module.exports.authStorage,legacy,secure};
}
test('session longue et arabe: migration sécurisée, chunks ASCII, restauration exacte et suppression',async()=>{const {storage,legacy,secure}=setup();const value=JSON.stringify({access_token:'x'.repeat(5000),user:{name:'محمد 🌙'}});legacy.set('sb-session',value);assert.equal(await storage.getItem('sb-session'),value);assert.equal(legacy.has('sb-session'),false);assert([...secure.values()].every(v=>Buffer.byteLength(v)<=1500));assert.equal(await storage.getItem('sb-session'),value);await storage.removeItem('sb-session');assert.equal(secure.size,0);});
test('une migration Keychain échouée conserve la session existante',async()=>{const {storage,legacy}=setup(true);legacy.set('sb-session','existing-session');await assert.rejects(storage.getItem('sb-session'));assert.equal(legacy.get('sb-session'),'existing-session');});
test('web conserve le stockage de session adapté à la plateforme',async()=>{const {storage,legacy,secure}=setup(false,'web');await storage.setItem('sb-session','session');assert.equal(await storage.getItem('sb-session'),'session');assert.equal(secure.size,0);assert.equal(legacy.get('sb-session'),'session');});
