const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module'),esbuild=require('esbuild');
async function harness(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'problem-report-')),output=path.join(dir,'service.cjs'),dbFile=path.join(dir,'queue.json');
 await esbuild.build({entryPoints:[path.resolve('src/services/problemReports.ts')],bundle:true,platform:'node',format:'cjs',outfile:output,external:['expo-sqlite','expo-file-system','expo-image-picker','@react-native-community/netinfo','react-native'],plugins:[{name:'problem-deps',setup(b){b.onResolve({filter:/^\.\/sync$/},()=>({path:'sync',namespace:'test'}));b.onResolve({filter:/^\.\/storage$/},()=>({path:'storage',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='sync'?'export const supabase=globalThis.reportTestBackend;':'export const loadState=()=>globalThis.reportTestState;',loader:'js'}));}}]});
 let rows=[],online=false,loseAck=false,writes=0;const records=new Map(),uploads=new Set();
 const db={execSync(){},getAllSync(sql,user){return rows.filter(r=>r.user_id===user);},getFirstSync(sql,...args){return rows.find(r=>sql.includes('WHERE user_id')?r.user_id===args[0]:r.id===args[0])||null;},runSync(sql,...args){if(sql.startsWith('INSERT'))rows.push({id:args[0],user_id:args[1],payload:args[2],local_uri:args[3],mime:args[4]});else rows=rows.filter(r=>r.id!==args[0]||r.user_id!==args[1]);fs.writeFileSync(dbFile,JSON.stringify(rows));}};
 class File{constructor(base,...parts){this.uri=path.join(typeof base==='string'?base:base.uri,...parts);}get size(){return fs.statSync(this.uri).size;}copy(file){fs.copyFileSync(this.uri,file.uri);}async bytes(){return fs.readFileSync(this.uri);}delete(){fs.unlinkSync(this.uri);}}
 class Directory extends File{create(){fs.mkdirSync(this.uri,{recursive:true});}}
 globalThis.reportTestState={userId:'alice'};
 globalThis.reportTestBackend={storage:{from(){return {async upload(name){if(!online)return {error:{message:'offline'}};if(uploads.has(name))return {error:{message:'The resource already exists',statusCode:'409'}};uploads.add(name);return {error:null};}};}},from(){return {async upsert(report){if(!online)return {error:{message:'offline'}};if(!records.has(report.id)){records.set(report.id,report);writes++;}if(loseAck){loseAck=false;return {error:{message:'lost acknowledgement'}};}return {error:null};},select(){const filters={};return {eq(key,value){filters[key]=value;return this;},async maybeSingle(){if(!online)return {error:{message:'offline'}};const report=records.get(filters.id);return {data:report?.user_id===filters.user_id?{id:report.id}:null,error:null};}};}};}};
 const original=Module._load;
 function load(){Module._load=function(name,...args){if(name==='expo-sqlite')return {openDatabaseSync:()=>db};if(name==='expo-file-system')return {File,Directory,Paths:{document:dir}};if(name==='expo-image-picker')return {};if(name==='@react-native-community/netinfo')return {fetch:async()=>({isConnected:online}),addEventListener:()=>()=>{}};if(name==='react-native')return {Platform:{OS:'ios'},AppState:{addEventListener:()=>({remove(){}})}};return original.call(this,name,...args);};try{delete require.cache[output];return require(output);}finally{Module._load=original;}}
 return {dir,load,get rows(){return rows;},get writes(){return writes;},online(){online=true;},loseAck(){loseAck=true;},restart(){rows=JSON.parse(fs.readFileSync(dbFile,'utf8'));},cleanup(){delete globalThis.reportTestState;delete globalThis.reportTestBackend;fs.rmSync(dir,{recursive:true,force:true});}};
}
test('report and screenshot persist offline; retry after server commit does not duplicate report or upload',async()=>{
 const h=await harness();try{let s=h.load();const capture=path.join(h.dir,'capture.jpg');fs.writeFileSync(capture,'test image');assert.equal(await s.sendProblemReport('Affichage','La page est décalée',{uri:capture,extension:'jpg',mime:'image/jpeg'}),'queued');assert.equal(h.rows.length,1);const local=h.rows[0].local_uri;assert.ok(fs.existsSync(local));fs.unlinkSync(capture);h.restart();s=h.load();h.online();h.loseAck();await assert.rejects(s.flushProblemReports());assert.equal(h.rows.length,1);assert.ok(fs.existsSync(local));await s.flushProblemReports();assert.equal(h.rows.length,0);assert.equal(h.writes,1);assert.equal(fs.existsSync(local),false);await s.flushProblemReports();assert.equal(h.writes,1);}finally{h.cleanup();}
});
test('report validation and account isolation preserve the correct owner',async()=>{
 const h=await harness();try{const s=h.load();await assert.rejects(s.sendProblemReport('Bug','   ',null),/500/);await assert.rejects(s.sendProblemReport('Bug','x'.repeat(501),null),/500/);assert.equal(h.rows.length,0);assert.equal(await s.sendProblemReport('Audio','Le lecteur ne démarre pas',null),'queued');globalThis.reportTestState.userId='bob';h.online();await s.flushProblemReports();assert.equal(h.rows.length,1);assert.equal(h.writes,0);globalThis.reportTestState.userId='alice';await s.flushProblemReports();assert.equal(h.rows.length,0);assert.equal(h.writes,1);}finally{h.cleanup();}
});
