const test=require('node:test'),assert=require('node:assert/strict');
const p=require('./build/core/program'),r=require('./build/core/review'),w=require('./build/core/weeklyProgress'),q=require('./build/core/quran'),z=require('./build/core/quranSources'),{createSyncWorker}=require('./build/core/offlineQueue');
function schedule(){const s=p.defaultState();s.onboardingDone=true;s.goal={label:'Test',ranges:[{start:1,end:7}]};s.pace='verse1';s.learningDays=[0,1,2,3,4,5,6];return p.generateProgram(s,'2026-10-05',20);}
for(const date of ['2026-10-05','2026-10-04','2026-10-07'])test('validation '+date+' ne dÃ©place aucune date prÃ©vue',()=>{const s=schedule(),old=s.sessions.map(x=>x.date);const next=p.completeSession(s,s.sessions[0].id,true,date);assert.deepEqual(next.sessions.map(x=>x.date),old);assert.equal(next.sessions[0].scheduledDate,'2026-10-05');assert.equal(next.sessions[0].completedDate,date);assert(next.sessions[0].completedAt);assert.equal(next.sessions[1].scheduledDate,'2026-10-06');});
test('effectuer mardi en avance lundi garde mardi et mercredi',()=>{let s=schedule();s=p.completeSession(s,s.sessions[0].id,true,'2026-10-05');s=p.completeSession(s,s.sessions[1].id,true,'2026-10-05');assert.equal(s.sessions[1].date,'2026-10-06');assert.equal(s.sessions[2].date,'2026-10-07');});
test('fenÃªtre prÃ©vue J Ã  J+10 sans effacer la planification',()=>{const s=schedule();assert(w.upcomingSessions(s,'2026-10-05').every(x=>x.date<='2026-10-15'));assert.equal(s.sessions.length,7);});
test('semaine locale dimanche/lundi, historique conservÃ©, DST Paris',()=>{const s=schedule();s.sessions[0]={...s.sessions[0],status:'done'};assert.equal(w.weeklyProgress(s,new Date('2026-10-11T23:59:00')).done,1);assert.equal(w.weeklyProgress(s,new Date('2026-10-12T00:01:00')).done,0);assert.equal(s.sessions[0].status,'done');const dst=w.weeklyProgress(s,new Date('2026-10-25T23:59:00'));assert.equal(dst.weekStart,'2026-10-19');assert.equal(dst.weekEnd,'2026-10-25');});
test('J+1/J+3/J+7 restent ancrÃ©s mÃªme en avance et sont indÃ©pendants des rÃ©visions',()=>{let s=schedule();s=p.completeSession(s,s.sessions[0].id,true,'2026-10-05');s=r.prepareReviewSchedule(s,'2026-10-05');assert.deepEqual(r.reviewPlan(s,'2026-10-05').consolidations[0].steps.map(x=>x.due),['2026-10-06','2026-10-08','2026-10-12']);s=r.completeConsolidation(s,{start:1,end:1},'2026-10-05','2026-10-05T20:00:00Z');assert.equal(s.reviewConsolidations[1].completed[1],'2026-10-05');assert.equal(s.reviewConsolidations[1].completedAt[1],'2026-10-05T20:00:00Z');assert.equal(r.reviewPlan(s,'2026-10-05').consolidations[0].steps[1].due,'2026-10-08');assert.equal(s.reviewHistory.length,0);});
test('difficultÃ© survit au succÃ¨s et Ã  une sÃ©rialisation, retrait explicite',()=>{let s=p.defaultState();s.knowledge[1]='perfect';s=r.toggleDifficulty(s,1,'2026-10-05');s=r.gradeReviewTask(s,{start:1,end:1,id:'a',category:'priority',label:''},'perfect','2026-10-05');s=JSON.parse(JSON.stringify(s));assert(s.difficultyMarkers[1].user);s=r.toggleDifficulty(s,1);assert.equal(s.difficultyMarkers[1],undefined);});
for(const quantity of ['nisf','hizb','juz','juz2'])test(quantity+' conserve uniquement les connaissances et toutes les divisions',()=>{const corpus=Array.from({length:q.juzs[2].end},(_,i)=>i+1).filter(id=>id%17!==0);const days=r.partitionDailyQuantity(corpus,quantity);assert.deepEqual(days.flat(),corpus);assert.equal(new Set(days.flat()).size,corpus.length);});
test('file hors ligne: Ã©chec conservÃ©, reconnexion, consommateurs sÃ©rialisÃ©s, une confirmation',async()=>{let rows=[{id:'1',userId:'u'}],calls=0,online=false;const flush=createSyncWorker({owner:()=> 'u',list:()=>rows.slice(),acknowledge:id=>{rows=rows.filter(x=>x.id!==id);}},async()=>{calls++;if(!online)throw Error('offline');await new Promise(r=>setTimeout(r,5));});await assert.rejects(flush());assert.equal(rows.length,1);online=true;await Promise.all([flush(),flush(),flush()]);assert.equal(rows.length,0);assert.equal(calls,2);await flush();assert.equal(calls,2);});
for(const source of ['coran_1441'])test(source+' 604 pages, 6236 versets, rectangles dans leurs images originales',()=>{const seen=new Set();for(let page=1;page<=604;page++){const {rows,dimensions:[width,height]}=z.zipPageData(source,page);assert(rows.length);assert(width>0&&height>0);for(const row of rows){assert(row[3]>=0&&row[4]<=width&&row[5]>=0&&row[6]<=height,JSON.stringify({page,row,width,height}));const id=q.verseId(row[0],row[1]);assert(id);seen.add(id);assert(z.zipVersePages(source,id).includes(page));}}assert.equal(seen.size,6236);});

test('double validation du mÃªme checkpoint ne valide jamais le suivant',()=>{let s=schedule();s=p.completeSession(s,s.sessions[0].id,true,'2026-10-05');s=r.completeConsolidation(s,{start:1,end:1},'2026-10-05','2026-10-05T18:00:00Z',1);s=r.completeConsolidation(s,{start:1,end:1},'2026-10-05','2026-10-05T18:00:01Z',1);assert.equal(s.reviewConsolidations[1].completed[3],undefined);});
test('une modification pendant la synchronisation ne disparaÃ®t pas avec la confirmation prÃ©cÃ©dente',async()=>{let rows=[{id:'1',userId:'u'}];const flush=createSyncWorker({owner:()=> 'u',list:()=>rows.slice(),acknowledge:id=>{rows=rows.filter(x=>x.id!==id);}},async()=>{rows.push({id:'2',userId:'u'});});await flush();assert.deepEqual(rows.map(x=>x.id),['2']);});

test('entrÃ©e locale immÃ©diate, aucune dÃ©pendance rÃ©seau pour un compte dÃ©jÃ  connectÃ©',()=>{const {initialAccountAccess}=require('./build/core/offlineAccess');const s=p.defaultState();assert.equal(initialAccountAccess({...s,userId:'cached-user'}),'done');assert.equal(initialAccountAccess(s),'show');});
test('historique des consolidations et cycles conservÃ© lors du passage au cycle suivant',()=>{let s=schedule();s=p.completeSession(s,s.sessions[0].id,true,'2026-10-05');for(const offset of [1,3,7])s=r.completeConsolidation(s,{start:1,end:1},p.addDays('2026-10-05',offset),'2026-10-05T20:00:00Z',offset);assert.equal(s.consolidationHistory.length,3);assert.deepEqual(s.consolidationHistory.map(e=>e.scheduledDate),['2026-10-06','2026-10-08','2026-10-12']);s=r.setReviewQuantity(s,'hizb','2026-10-13');assert(s.reviewCycleHistory.length);assert.equal(s.consolidationHistory.length,3);});

test('fusion offline: prÃ©fÃ©rence locale, apprentissage distant et retrait volontaire de difficultÃ© conservÃ©s',()=>{const {mergeOfflineState}=require('./build/core/offlineMerge');const base={...p.defaultState(),userId:'u',onboardingDone:true,difficultyMarkers:{1:{user:{createdAt:'2026-10-03'}}}};const local={...base,theme:'feminine',difficultyMarkers:{}};const remote={...base,knowledge:{2:'perfect'},difficultyMarkers:{1:{...base.difficultyMarkers[1],admin:{createdAt:'2026-10-03'}}}};const merged=mergeOfflineState(base,local,remote);assert.equal(merged.theme,'feminine');assert.equal(merged.knowledge[2],'perfect');assert.equal(merged.difficultyMarkers[1].user,undefined);assert(merged.difficultyMarkers[1].admin);});

test('un ancien programme court est prolongÃ© Ã  mardi sans recrÃ©er lundi',()=>{let s=schedule();s.sessions=s.sessions.slice(0,1);const first=s.sessions[0].id;s=p.completeSession(s,first,true,'2026-10-05');assert.equal(s.sessions[0].id,first);assert.equal(s.sessions[0].date,'2026-10-05');assert.equal(s.sessions[1].date,'2026-10-06');assert.equal(s.sessions[1].start,2);});

test('anciennes sources de test migrent vers Coran 1441 sans perdre les données',()=>{for(const source of ['tawjeed_test_2','tajweed_test_2','medine_test']){const state=p.defaultState();state.reader.mushaf=source;state.knowledge[1]='perfect';const migrated=p.migrateReaderState(state);assert.equal(migrated.reader.mushaf,'coran_1441');assert.equal(migrated.knowledge,state.knowledge);}});
