const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module'),esbuild=require('esbuild');
async function harness(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'quiz-offline-')),output=path.join(dir,'service.cjs'),file=path.join(dir,'sqlite.json');
 await esbuild.build({entryPoints:[path.resolve('src/services/quiz.ts')],bundle:true,platform:'node',format:'cjs',outfile:output,external:['expo-sqlite','@react-native-community/netinfo','react-native','react'],plugins:[{name:'quiz-deps',setup(build){build.onResolve({filter:/^\.\/sync$/},()=>({path:'sync',namespace:'test'}));build.onResolve({filter:/^\.\/storage$/},()=>({path:'storage',namespace:'test'}));build.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='sync'?'export const supabase=globalThis.quizTestBackend;':'export const loadState=()=>globalThis.quizTestState;',loader:'js'}));}}]});
 let disk={cache:{},outbox:[]},network=false,failAfterCommit=false,serverWrites=0;const responses=new Map();
 const persist=()=>fs.writeFileSync(file,JSON.stringify(disk));
 const db={execSync(){},withTransactionSync(fn){fn();},getAllSync(sql,user){return disk.outbox.filter(r=>r.user_id===user);},getFirstSync(sql,user){if(sql.includes('quiz_cache'))return disk.cache[user]?{data:disk.cache[user]}:null;return disk.outbox.find(r=>r.user_id===user)||null;},runSync(sql,...args){if(sql.startsWith('INSERT INTO quiz_cache'))disk.cache[args[0]]=args[1];else if(sql.startsWith('INSERT OR IGNORE')){if(!disk.outbox.some(r=>r.id===args[0]))disk.outbox.push({id:args[0],user_id:args[1],payload:args[2],created_at:args[3]});}else if(sql.startsWith('DELETE'))disk.outbox=disk.outbox.filter(r=>r.id!==args[0]||r.user_id!==args[1]);persist();}};
 globalThis.quizTestState={userId:'alice'};
 const question={id:'daily',category:'Coran',publicationDate:new Date().toLocaleDateString('en-CA'),question:'Test',answers:[{id:'A',text:'A'},{id:'B',text:'B'},{id:'C',text:'C'}]};
 globalThis.quizTestBackend={async rpc(name,args){if(!network)throw new Error('offline');const user=globalThis.quizTestState.userId;if(name==='quiz_answer_daily'){const key=user+args.p_day;if(!responses.has(key)){serverWrites++;responses.set(key,{questionId:question.id,day:args.p_day,selectedAnswerId:args.p_answer,answeredAt:args.p_answered_at,isCorrect:args.p_answer==='B',question:{...question,correctAnswerId:'B'}});}if(failAfterCommit){failAfterCommit=false;throw new Error('connection lost after server commit');}return {data:null};}return {data:{day:question.publicationDate,daily:question,responses:[...responses].filter(([key])=>key.startsWith(user)).map(([,r])=>r),challenges:[]}};}};
 const original=Module._load;
 function load(){Module._load=function(name,...args){if(name==='react')return {useEffect(){},useState(){}};if(name==='expo-sqlite')return {openDatabaseSync:()=>db};if(name==='@react-native-community/netinfo')return {fetch:async()=>({isConnected:network}),addEventListener:()=>()=>{}};if(name==='react-native')return {AppState:{addEventListener:()=>({remove(){}})}};return original.call(this,name,...args);};try{delete require.cache[output];return require(output);}finally{Module._load=original;}}
 return {load,question,get queue(){return disk.outbox.length;},get writes(){return serverWrites;},online(){network=true;},loseAcknowledgement(){failAfterCommit=true;},restart(){disk=JSON.parse(fs.readFileSync(file,'utf8'));},cleanup(){delete globalThis.quizTestState;delete globalThis.quizTestBackend;fs.rmSync(dir,{recursive:true,force:true});}};
}
test('daily offline answer survives restart, cannot change, retries an unacknowledged server commit once',async()=>{
 const h=await harness();try{let s=h.load();s.answerDaily(h.question,'A');await assert.rejects(s.refreshQuiz(),/offline/);assert.equal(h.queue,1);s.answerDaily(h.question,'B');assert.equal(s.cachedQuiz('alice').responses[0].selectedAnswerId,'A');h.restart();s=h.load();assert.equal(s.cachedQuiz('alice').responses[0].pending,true);h.online();h.loseAcknowledgement();await assert.rejects(s.refreshQuiz(),/connection lost/);assert.equal(h.queue,1);await s.refreshQuiz();assert.equal(h.queue,0);assert.equal(h.writes,1);assert.equal(s.cachedQuiz('alice').responses[0].isCorrect,false);assert.equal(s.cachedQuiz('alice').responses[0].pending,undefined);await s.refreshQuiz();assert.equal(h.writes,1);}finally{h.cleanup();}
});
test('cached quiz and queued operations remain isolated between accounts',async()=>{
 const h=await harness();try{const s=h.load();s.answerDaily(h.question,'B');await assert.rejects(s.refreshQuiz(),/offline/);globalThis.quizTestState.userId='bob';assert.equal(s.cachedQuiz('bob').responses.length,0);h.online();await s.refreshQuiz();assert.equal(h.queue,1);assert.equal(h.writes,0);globalThis.quizTestState.userId='alice';await s.refreshQuiz();assert.equal(h.queue,0);assert.equal(h.writes,1);}finally{h.cleanup();}
});
