const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
test('Quiz PostgreSQL: rights, one daily answer, frozen shared questions, hidden corrections, scores and expiry',async()=>{
 const db=new PGlite();const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',outsider='00000000-0000-0000-0000-000000000003';
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function private.is_app_admin() returns boolean language sql as $$select current_setting('test.admin',true)='true'$$;create table notification_preferences(user_id uuid primary key,messages_enabled boolean default true);create table public.friend_profiles(id uuid primary key,display_name text,avatar_path text);create table public.friend_links(requester_id uuid,recipient_id uuid,status text);insert into auth.users values('${a}'),('${b}'),('${outsider}');insert into friend_profiles values('${a}','Mohamed',null),('${b}','Yassine',null);insert into friend_links values('${a}','${b}','accepted');`);
 const migration=fs.readFileSync('supabase/quiz.sql','utf8');await db.exec(migration);await db.exec(migration);
 await db.exec(`create table push_devices(user_id uuid,expo_push_token text);create table push_log(body jsonb);create function private.send_expo_push(url text,body jsonb,headers jsonb,timeout_milliseconds integer default 5000) returns bigint language plpgsql as $$begin insert into public.push_log values(body);return 1;end$$;create schema cron;create table cron.job(jobname text);create function cron.schedule(text,text,text) returns bigint language plpgsql as $$begin insert into cron.job values($1);return 1;end$$;insert into push_devices values('${a}','ExpoPushToken[a]'),('${b}','ExpoPushToken[b]');`);
 const notifications=fs.readFileSync('supabase/quiz-notifications.sql','utf8').replace('create extension if not exists pg_cron;','');await db.exec(notifications);await db.exec(notifications);
 const asUser=async(id,admin=false)=>{await db.query("select set_config('test.uid',$1,false),set_config('test.admin',$2,false)",[id,String(admin)]);};
 await asUser(a,true);const day=(await db.query('select current_date::text as day')).rows[0].day,at=new Date().toISOString();let dailyId;
 for(let i=0;i<10;i++){const q={category:'Coran',question:'Question de test '+i,answers:['A','B','C'].map(id=>({id,text:id})),correctAnswerId:'B',explanation:'Explication de test',sourceTitle:'Source de test',publicationDate:day,isDailyQuestion:i===0,availableForChallenges:true,isActive:true};const r=await db.query('select quiz_admin_save($1::jsonb) as id',[JSON.stringify(q)]);if(i===0)dailyId=r.rows[0].id;}
 const questionIds=(await db.query('select id from quiz_questions order by created_at,id')).rows.map(q=>q.id);
 const setDraft={title:'Coran — quiz thématique',category:'Coran',questionIds,isActive:true};
 await assert.rejects(db.query('select quiz_admin_save_set($1::jsonb)',[JSON.stringify({...setDraft,questionIds:questionIds.slice(0,9)})]),/exactement 10/);
 await assert.rejects(db.query('select quiz_admin_save_set($1::jsonb)',[JSON.stringify({...setDraft,questionIds:Array(10).fill(questionIds[0])})]),/exactement 10/);
 const setId=(await db.query('select quiz_admin_save_set($1::jsonb) as id',[JSON.stringify(setDraft)])).rows[0].id;
 assert.equal((await db.query('select quiz_admin_sets() as s')).rows[0].s[0].title,setDraft.title);
 await assert.rejects(db.query('select quiz_admin_save($1::jsonb)',[JSON.stringify({category:'Coran',question:'Deuxième quotidienne',answers:['A','B','C'].map(id=>({id,text:id})),correctAnswerId:'A',sourceTitle:'Test',publicationDate:day,isDailyQuestion:true})]),/duplicate/);
 await asUser(a);const snapshot=async()=> (await db.query('select quiz_snapshot($1) as s',[day])).rows[0].s;
 let s=await snapshot();assert.equal(s.daily.correctAnswerId,undefined);assert.equal(s.daily.explanation,undefined);
 await assert.rejects(db.query('select quiz_admin_list()'),/administrateur/);await assert.rejects(db.query('select quiz_admin_sets()'),/administrateur/);assert.equal(s.quizSets[0].title,setDraft.title);assert.equal(s.quizSets[0].questionIds,undefined);
 await db.exec('set role authenticated');await assert.rejects(db.query('select * from quiz_questions'),/permission denied/);await db.exec('reset role');
 await db.query('select quiz_answer_daily($1,$2,$3,$4)',[dailyId,'A',day,at]);await db.query('select quiz_answer_daily($1,$2,$3,$4)',[dailyId,'B',day,at]);s=await snapshot();assert.equal(s.responses.length,1);assert.equal(s.responses[0].selectedAnswerId,'A');assert.equal(s.responses[0].isCorrect,false);assert.equal(s.responses[0].question.correctAnswerId,'B');
 const cid=(await db.query('select quiz_create_challenge($1,10,$2) as id',[b,setId])).rows[0].id;let c=(await snapshot()).challenges[0],ids=c.questions.map(q=>q.id);assert.equal(ids.length,10);assert.deepEqual(ids,questionIds);assert.equal(new Set(ids).size,10);assert.equal(Math.round((Date.parse(c.expiresAt)-Date.parse(c.createdAt))/3600000),48);
 await asUser(b);assert.deepEqual((await snapshot()).challenges[0].questions.map(q=>q.id),ids);
 await asUser(outsider);assert.equal((await snapshot()).challenges.length,0);await assert.rejects(db.query('select quiz_answer_challenge($1,$2,$3)',[cid,ids[0],'B']),/inaccessible/);await assert.rejects(db.query('select quiz_create_challenge($1,5)',[a]),/ami/);
 await asUser(a);for(const id of ids)await db.query('select quiz_answer_challenge($1,$2,$3)',[cid,id,'B']);c=(await snapshot()).challenges[0];assert.equal(c.status,'pending');assert.equal(c.answers[0].isCorrect,undefined);assert.equal(c.questions[0].explanation,undefined);await db.query('select quiz_answer_challenge($1,$2,$3)',[cid,ids[0],'A']);assert.equal((await snapshot()).challenges[0].answers.length,10);
 await asUser(b);for(const id of ids)await db.query('select quiz_answer_challenge($1,$2,$3)',[cid,id,'A']);c=(await snapshot()).challenges[0];assert.equal(c.status,'completed');assert.equal(c.answers.filter(x=>x.userId===a&&x.isCorrect).length,10);assert.equal(c.answers.filter(x=>x.userId===b&&x.isCorrect).length,0);assert.equal(c.questions[0].explanation,'Explication de test');assert.ok(c.completedAt);
 const small=(await db.query('select quiz_create_challenge($1,5) as id',[a])).rows[0].id;await db.query("update quiz_challenges set expires_at=now()-interval '1 second' where id=$1",[small]);c=(await snapshot()).challenges.find(x=>x.id===small);assert.equal(c.status,'expired');await assert.rejects(db.query('select quiz_answer_challenge($1,$2,$3)',[small,c.questions[0].id,'B']),/expiré/);
 assert.equal((await db.query("select count(*)::integer as n from push_log where body->>'title' like '%te défie%'")).rows[0].n,2);
 assert.equal((await db.query("select count(*)::integer as n from push_log where body->>'title'='Résultat disponible 🏆'")).rows[0].n,2);
 assert.equal((await db.query("select count(*)::integer as n from push_log where body->>'title' like '%a terminé son quiz%'")).rows[0].n,1);
 await asUser(a);await db.query('select quiz_set_notifications(false,$1)',['Europe/Paris']);await db.query("select private.quiz_push($1,'disabled','Test','Test','{}')",[a]);assert.equal((await db.query("select count(*)::integer as n from push_log where body->>'title'='Test'")).rows[0].n,0);
 await db.query('select private.quiz_notify_daily()');await db.query('select private.quiz_notify_daily()');
 await asUser(a,true);await db.query('select quiz_admin_delete($1)',[dailyId]);await asUser(a);assert.equal((await snapshot()).responses[0].question.question,'Question de test 0');assert.equal((await snapshot()).challenges.find(x=>x.id===cid).questions.length,10);
 }finally{await db.close();}
});
