const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,mocks,React){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,console,require:name=>name==='react'?React:mocks[name]??(()=>{throw Error(name)})()});return exports;}
const createElement=(type,props,...children)=>({type,props:props??{},children});
function find(node,label){if(!node||typeof node!=='object')return null;if(Array.isArray(node)){for(const n of node){const r=find(n,label);if(r)return r;}return null;}if(node.props?.accessibilityLabel===label)return node;return find(node.children,label);}
function recorderHarness(){let cursor=0;let range={start:1,end:7};const states=[],calls=[],saved=[];const React={createElement,useState(init){const i=cursor++;if(!(i in states))states[i]=typeof init==='function'?init():init;return [states[i],v=>states[i]=typeof v==='function'?v(states[i]):v];},useRef(init){const i=cursor++;return states[i]??(states[i]={current:init});},useEffect(){}};
 const recorder={uri:'file:///draft.m4a',prepareToRecordAsync:async()=>calls.push('prepare'),record:()=>calls.push('record'),pause:()=>calls.push('pause'),stop:async()=>calls.push('stop'),getStatus:()=>({durationMillis:5000})};
 const component=load('src/RecitationRecorder.tsx',{'react-native':{View:'View',Pressable:'Pressable',Alert:{alert(){}}},'./ui/Premium':{Icon:'Icon'},'./ui/theme':{Button:'Button',Card:'Card',Label:'Label',colors:{}},'@react-native-async-storage/async-storage':{getItem:async()=> 'yes'},'expo-audio':{AudioQuality:{MEDIUM:1},RecordingPresets:{HIGH_QUALITY:{ios:{}}},requestRecordingPermissionsAsync:async()=>({granted:true}),setAudioModeAsync:async()=>{},useAudioRecorder:()=>recorder,useAudioRecorderState:()=>({durationMillis:5000})},'./services/audioFocus':{stopActiveAudio(){},createManagedAudioPlayer:()=>({play:()=>calls.push('play'),pause(){},release(){}})},'./core/quran':{reference:()=> 'Al Fatiha 1–7'},'./services/sync':{supabase:{auth:{getSession:async()=>({data:{session:{user:{id:'user-1'}}}})}}},'./services/recitations':{saveLocalRecitation:async(...args)=>{saved.push(args);return {id:'rec-1',uri:args[0],durationMs:args[3]};},syncPendingRecitations:async()=>calls.push('sync')}},React).RecitationRecorder;
 const render=()=>{cursor=0;return component({compact:true,range});};return {setRange:value=>range=value,press:async label=>{const button=find(render(),label);assert.ok(button,label);await button.props.onPress();},has:label=>!!find(render(),label),calls,saved};}
test('enregistrement compact : pause, aperçu puis sauvegarde explicite dans le service existant',async()=>{const c=recorderHarness();await c.press('Commencer');await c.press('Pause');assert.ok(c.has('Reprendre'));await c.press('Reprendre');await c.press('Terminer');assert.equal(c.saved.length,0);await c.press('Réécouter');assert.ok(c.calls.includes('play'));await c.press('Enregistrer');assert.deepEqual(c.saved[0],['file:///draft.m4a',1,7,5000,'user-1',undefined]);assert.ok(c.calls.includes('sync'));});
test('recommencer un brouillon ne sauvegarde aucune récitation',async()=>{const c=recorderHarness();await c.press('Commencer');await c.press('Terminer');await c.press('Recommencer');assert.ok(c.has('Commencer'));assert.equal(c.saved.length,0);});
test('la barre commune garde les cinq actions dans tous les contextes',()=>{const React={createElement,Fragment:'Fragment'};const ui=load('src/ui/ImmersiveReaderChrome.tsx',{'react-native':{Pressable:'Pressable',View:'View'},'./Premium':{Icon:'Icon',premiumShadow:{}},'./theme':{Label:'Label',colors:{}}},React).ReaderFloatingActions;const props={active:null,onHome(){},onAudio(){},onRecord(){},onBookmark(){},onMore(){}};const normal=ui(props);for(const label of ['Accueil','Écouter','Enregistrer','Marque-page','Plus'])assert.ok(find(normal,label));assert.equal(find(normal,'Traduction'),null);});
test('le choix explicite verse-files garde les fichiers de l’IPA',async()=>{const React={};const service=load('src/services/quranAudioTimeline.ts',{'@react-native-async-storage/async-storage':{getItem(){throw Error('ne doit pas lire de timing');}},'../core/audio':{},'../core/quran':{}},React);assert.equal(await service.chapterAudio(73,{id:'ar.alafasy'},'verse-files'),null);});

test('le brouillon garde le passage enregistré après un changement de page',async()=>{const c=recorderHarness();await c.press('Commencer');await c.press('Terminer');c.setRange({start:8,end:12});await c.press('Enregistrer');assert.deepEqual(c.saved[0].slice(1,3),[1,7]);});
