import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,View} from 'react-native';
import {Button,Card,CheckChoice,Choice,Field,Label,colors} from './theme';
import {Heading,SectionHeader} from './DesignSystem';
import {QuizQuestion,quizCategories,quizDay} from '../core/quiz';
import {AdminQuizSets} from './AdminQuizSets';
import {quizRpc} from '../services/quiz';
const fresh=():QuizQuestion=>({id:'',category:'Coran',question:'',answers:['A','B','C','D'].map(id=>({id,text:''})),correctAnswerId:'A',explanation:'',sourceTitle:'',sourceReference:'',sourceUrl:'',publicationDate:quizDay(),isDailyQuestion:false,availableForChallenges:true,isActive:true});
export function AdminQuiz({onClose}:{onClose:()=>void}){
 const [section,setSection]=useState<'questions'|'sets'>('questions');
 const [rows,setRows]=useState<QuizQuestion[]>([]),[draft,setDraft]=useState<QuizQuestion|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setRows(await quizRpc('quiz_admin_list'));
 useEffect(()=>{void load().catch(e=>setNotice(e.message));},[]);
 const act=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);try{await fn();await load();setNotice('Question enregistrée.');}catch(e){setNotice(e instanceof Error?e.message:'Erreur du service Quiz.');}finally{setBusy(false);}};
 const change=(key:keyof QuizQuestion,value:unknown)=>setDraft(d=>d?{...d,[key]:value}:d);
 const valid=draft&&draft.question.trim()&&draft.sourceTitle?.trim()&&draft.answers.filter(a=>a.text.trim()).length>=3&&draft.answers.some(a=>a.id===draft.correctAnswerId&&a.text.trim())&&(!draft.isDailyQuestion||/^\d{4}-\d{2}-\d{2}$/.test(draft.publicationDate??''));
 if(section==='sets')return <AdminQuizSets questions={rows} onClose={()=>setSection('questions')}/>;
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:40}}><Button secondary onPress={()=>draft?setDraft(null):onClose()}>← {draft?'Liste des questions':'Administration'}</Button><Heading size={26}>Quiz</Heading>{!!notice&&<Card><Label style={{fontSize:13}}>{notice}</Label></Card>}{draft?<>
 <SectionHeader title="Catégorie"/>{quizCategories.map(c=><Choice key={c} label={c} selected={draft.category===c} onPress={()=>change('category',c)}/>)}
 <SectionHeader title="Question"/><Field value={draft.question} onChangeText={v=>change('question',v)} placeholder="Question" multiline/>
 <SectionHeader title="Réponses · 3 ou 4 propositions"/>{draft.answers.map((a,i)=><View key={a.id}><Field value={a.text} onChangeText={v=>setDraft(d=>d?{...d,answers:d.answers.map(x=>x.id===a.id?{...x,text:v}:x)}:d)} placeholder={`Réponse ${String.fromCharCode(65+i)}${i===3?' (facultative)':''}`}/><Choice label={`Bonne réponse : ${String.fromCharCode(65+i)}`} selected={draft.correctAnswerId===a.id} onPress={()=>change('correctAnswerId',a.id)}/></View>)}
 <SectionHeader title="Explication et source"/>{(['explanation','sourceTitle','sourceReference','sourceUrl','arabic','translation'] as const).map((key,i)=><Field key={key} value={draft[key]??''} onChangeText={v=>change(key,v)} placeholder={['Explication','Source (obligatoire)','Référence','Lien HTTPS (facultatif)','Arabe (facultatif)','Traduction (facultative)'][i]} multiline={key==='explanation'||key==='arabic'||key==='translation'}/>)}
 <Field value={String(draft.surah??'')} onChangeText={v=>change('surah',v?Number(v):null)} keyboardType="number-pad" placeholder="Sourate (facultative)"/><Field value={String(draft.ayah??'')} onChangeText={v=>change('ayah',v?Number(v):null)} keyboardType="number-pad" placeholder="Verset (facultatif)"/>
 <SectionHeader title="Publication"/><Field value={draft.publicationDate??''} onChangeText={v=>change('publicationDate',v)} placeholder="Date · AAAA-MM-JJ"/><CheckChoice label="Question du jour" selected={!!draft.isDailyQuestion} onPress={()=>change('isDailyQuestion',!draft.isDailyQuestion)}/><CheckChoice label="Disponible pour les défis" selected={!!draft.availableForChallenges} onPress={()=>change('availableForChallenges',!draft.availableForChallenges)}/><CheckChoice label="Active" selected={!!draft.isActive} onPress={()=>change('isActive',!draft.isActive)}/><Label style={{fontSize:12,color:colors.muted}}>Une seule question active peut être publiée pour une date donnée. Les défis et corrections déjà enregistrés gardent leur contenu d’origine.</Label><Button disabled={!valid||busy} onPress={()=>void act(async()=>{await quizRpc('quiz_admin_save',{p_question:{...draft,answers:draft.answers.filter(a=>a.text.trim())}});setDraft(null);})}>Enregistrer la question</Button>
 </>:<><SectionHeader title="Questions du jour"/><Label style={{fontSize:13,color:colors.muted}}>Crée une question et choisis sa date de publication.</Label><Button secondary onPress={()=>setSection('sets')}>Quiz thématiques · 10 questions</Button><Button onPress={()=>setDraft(fresh())}>+ Nouvelle question</Button>{rows.map(q=><Card key={q.id}><Heading size={18}>{q.question}</Heading><Label style={{fontSize:12,color:colors.muted,marginTop:6}}>{q.category} · {q.publicationDate??'Défis'} · {q.isActive?'Active':'Inactive'}</Label><Button small onPress={()=>setDraft({...q,answers:q.answers.length===3?[...q.answers,{id:'D',text:''}]:q.answers})}>Modifier</Button><Button small secondary onPress={()=>setDraft({...q,id:'',publicationDate:quizDay(),isDailyQuestion:false})}>Dupliquer</Button><Button small secondary disabled={busy} onPress={()=>void act(()=>quizRpc('quiz_admin_save',{p_question:{...q,isActive:!q.isActive}}))}>{q.isActive?'Désactiver':'Activer'}</Button><Button small secondary disabled={busy} onPress={()=>Alert.alert('Supprimer cette question ?','Les réponses et défis déjà enregistrés conserveront leur contenu.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>void act(()=>quizRpc('quiz_admin_delete',{p_id:q.id}))}])}>Supprimer</Button></Card>)}</>}</ScrollView>;
}
