import React,{useEffect,useState} from 'react';
import {FlatList,Image,Modal,Pressable,View} from 'react-native';
import {Button,Card,Label,colors} from './theme';
import {Heading} from './DesignSystem';
import {adminProblemReports,ProblemReport,problemScreenshotUrl,resolveProblemReport} from '../services/problemReports';
export function AdminProblemReports({onClose}:{onClose:()=>void}){
 const [rows,setRows]=useState<ProblemReport[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[image,setImage]=useState<string|null>(null);
 const load=async()=>setRows(await adminProblemReports());
 useEffect(()=>{void load().catch(e=>setNotice(e.message));},[]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'Erreur de chargement.');}finally{setBusy(false);}};
 return <><FlatList data={rows} keyExtractor={r=>r.id} contentContainerStyle={{padding:18,paddingBottom:40}} ListHeaderComponent={<><Button secondary onPress={onClose}>← Administration</Button><Heading size={25}>Problèmes de l’application</Heading><Label style={{fontSize:12,color:colors.muted,marginVertical:8}}>Les captures sont privées et accessibles uniquement à leur auteur et aux administrateurs.</Label>{!!notice&&<Card><Label>{notice}</Label></Card>}<Button secondary disabled={busy} onPress={()=>void act(load)}>Actualiser</Button></>} ListEmptyComponent={<Label>Aucun signalement disponible.</Label>} renderItem={({item:r})=><Card><Heading size={18}>{r.type} · {r.status==='open'?'À traiter':'Traité'}</Heading><Label selectable style={{fontSize:14,marginVertical:9}}>{r.description}</Label><Label style={{fontSize:11,color:colors.muted}}>{new Date(r.created_at).toLocaleString('fr-FR')} · {r.platform} · v{r.app_version}</Label><Label style={{fontSize:10,color:colors.muted,marginTop:4}}>Compte · {r.user_id}</Label>{r.screenshot_path&&<Button small secondary disabled={busy} onPress={()=>void act(async()=>setImage(await problemScreenshotUrl(r.screenshot_path!)))}>Voir la capture</Button>}<Button small disabled={busy} secondary={r.status==='resolved'} onPress={()=>void act(async()=>{await resolveProblemReport(r.id,r.status==='open');await load();})}>{r.status==='open'?'Marquer comme traité':'Rouvrir'}</Button></Card>}/><Modal visible={!!image} transparent animationType="fade" onRequestClose={()=>setImage(null)}><View style={{flex:1,backgroundColor:'#000D',padding:20,justifyContent:'center'}}>{image&&<Image source={{uri:image}} resizeMode="contain" style={{width:'100%',height:'80%'}}/>}<Button onPress={()=>setImage(null)}>Fermer la capture</Button></View></Modal></>;
}
