import React,{useEffect,useState} from 'react';
import {Alert,ScrollView} from 'react-native';
import {Button,Card,CheckChoice,Choice,Field,Label,colors} from './theme';
import {Heading,SectionHeader} from './DesignSystem';
import {QuizQuestion,ThemedQuiz,quizCategories} from '../core/quiz';
import {quizRpc} from '../services/quiz';

export function AdminQuizSets({questions,onClose}:{questions:QuizQuestion[];onClose:()=>void}){
 const [rows,setRows]=useState<ThemedQuiz[]>([]),[draft,setDraft]=useState<ThemedQuiz|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>setRows(await quizRpc('quiz_admin_sets'));
 useEffect(()=>{void load().catch(e=>setNotice(e.message));},[]);
 const act=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);try{await fn();await load();setDraft(null);setNotice('Quiz enregistré.');}catch(e){setNotice(e instanceof Error?e.message:'Impossible d’enregistrer ce quiz.');}finally{setBusy(false);}};
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:40}}><Button secondary onPress={()=>draft?setDraft(null):onClose()}>← {draft?'Quiz thématiques':'Questions du jour'}</Button><Heading size={26}>Quiz thématiques</Heading><Label style={{fontSize:13,color:colors.muted}}>Chaque quiz contient exactement 10 questions. Il est disponible pour les défis entre amis.</Label>{!!notice&&<Card><Label>{notice}</Label></Card>}{draft?<><Field placeholder="Nom du quiz" value={draft.title} onChangeText={title=>setDraft({...draft,title})}/><SectionHeader title="Thème"/>{quizCategories.map(category=><Choice key={category} label={category} selected={category===draft.category} onPress={()=>setDraft({...draft,category})}/>)}<SectionHeader title={`Questions · ${draft.questionIds?.length??0} / 10`}/>{questions.filter(q=>q.isActive&&q.availableForChallenges).map(q=><CheckChoice key={q.id} label={`${q.category} · ${q.question}`} selected={draft.questionIds?.includes(q.id)??false} onPress={()=>{const ids=draft.questionIds??[];if(ids.includes(q.id))setDraft({...draft,questionIds:ids.filter(id=>id!==q.id)});else if(ids.length<10)setDraft({...draft,questionIds:[...ids,q.id]});}}/>)}<CheckChoice label="Quiz actif" selected={draft.isActive!==false} onPress={()=>setDraft({...draft,isActive:!draft.isActive})}/><Button disabled={busy||!draft.title.trim()||draft.questionIds?.length!==10} onPress={()=>void act(()=>quizRpc('quiz_admin_save_set',{p_set:draft}))}>Enregistrer le quiz</Button></>:<><Button onPress={()=>setDraft({id:'',title:'',category:'Coran',questionIds:[],isActive:true})}>+ Nouveau quiz de 10 questions</Button>{rows.map(q=><Card key={q.id}><Heading size={18}>{q.title}</Heading><Label>{q.category} · 10 questions · {q.isActive?'Actif':'Inactif'}</Label><Button small onPress={()=>setDraft(q)}>Modifier</Button><Button small secondary onPress={()=>setDraft({...q,id:'',title:`${q.title} (copie)`})}>Dupliquer</Button><Button small secondary disabled={busy} onPress={()=>void act(()=>quizRpc('quiz_admin_save_set',{p_set:{...q,isActive:!q.isActive}}))}>{q.isActive?'Désactiver':'Activer'}</Button><Button small secondary disabled={busy} onPress={()=>Alert.alert('Supprimer ce quiz ?','Les défis déjà créés sont conservés.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>void act(()=>quizRpc('quiz_admin_delete_set',{p_id:q.id}))}])}>Supprimer</Button></Card>)}</>}</ScrollView>;
}
