import React,{useState} from 'react';
import {Image,Pressable,Text,View} from 'react-native';
import {AppTheme,AccentName} from '../core/program';
import {colors,Card,Button,Label,accents,themeOptions} from './theme';
import {Icon,IconName,ProgressTrack,themeArt} from './Premium';
import {titleFont,arabicFont} from '../theme/fonts';
export {Card as AppCard,Button as PrimaryButton,ProgressTrack as ProgressBar};
export const readingArt=require('../../assets/illustrations/reading.png');
export function Heading({children,size=21,color=colors.green}:{children:React.ReactNode;size?:number;color?:string}){return <Label style={{fontFamily:titleFont(),fontSize:size,lineHeight:size*1.2,fontWeight:'600',color}}>{children}</Label>;}
export function ArabicLabel({children,size=22,color=colors.green}:{children:React.ReactNode;size?:number;color?:string}){return <Label numberOfLines={1} style={{fontFamily:arabicFont(),fontSize:size,lineHeight:size*1.55,color,textAlign:'right',writingDirection:'rtl'}}>{children}</Label>;}
export function IconButton({name,label,onPress,disabled=false}:{name:IconName;label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} accessibilityState={{disabled}} accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:16}}><Icon name={name} color={colors.green} size={24}/></Pressable>;}
export function SectionHeader({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:6,marginBottom:8,gap:8}}><Heading>{title}</Heading>{action&&onPress&&<Pressable accessibilityRole="button" onPress={onPress} style={{minHeight:44,flexDirection:'row',alignItems:'center'}}><Label style={{fontSize:12,color:colors.green}}>{action}</Label><Icon name="chevron-right" size={17} color={colors.green}/></Pressable>}</View>;}
export function SegmentedControl<T extends string>({options,value,onChange}:{options:readonly T[];value:T;onChange:(value:T)=>void}){return <View accessibilityRole="tablist" style={{flexDirection:'row',backgroundColor:colors.surfaceSecondary,borderRadius:16,padding:3,borderWidth:1,borderColor:colors.line,marginVertical:8}}>{options.map(option=><Pressable key={option} accessibilityRole="tab" accessibilityState={{selected:value===option}} onPress={()=>onChange(option)} style={{flex:1,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:13,backgroundColor:value===option?colors.green:'transparent'}}><Label style={{fontSize:14,color:value===option?'white':colors.muted,fontFamily:titleFont()}}>{option}</Label></Pressable>)}</View>;}
export function QuranNumberMedallion({number}:{number:number}){return <View style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Image source={require('../../assets/illustrations/medallion.png')} style={{position:'absolute',width:44,height:44}}/><Text style={{fontFamily:titleFont(),fontSize:20,color:colors.text}}>{number}</Text></View>;}
export function DailyTaskCard({title,passage,details,onPress,revision=false}:{title:string;passage:string;details:string;onPress:()=>void;revision?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={{flex:1,minHeight:100,backgroundColor:colors.paper,borderRadius:18,borderWidth:1,borderColor:colors.line,padding:10}}><View style={{position:'absolute',left:10,top:12,width:30,height:30,borderRadius:15,backgroundColor:revision?colors.reviewSoft:colors.selected,alignItems:'center',justifyContent:'center'}}><Icon name={revision?'autorenew':'book-open-outline'} size={20} color={revision?colors.review:colors.green}/></View><View style={{marginLeft:36}}><Heading size={14} color={revision?colors.review:colors.green}>{title}</Heading><Label numberOfLines={2} style={{fontSize:12,lineHeight:18,marginTop:5}}>{passage}</Label><Label style={{fontSize:10,color:colors.muted,marginTop:5,paddingRight:10}}>{details}</Label></View><View style={{position:'absolute',right:4,bottom:8}}><Icon name="chevron-right" size={16} color={colors.muted}/></View></Pressable>;}
export function StatCard({title,value,icon,children}:{title:string;value:string|number;icon:IconName;children?:React.ReactNode}){return <Card style={{flex:1,minHeight:100,padding:12}}><View style={{flexDirection:'row',gap:9,alignItems:'center'}}><View style={{width:35,height:35,borderRadius:18,backgroundColor:colors.selected,alignItems:'center',justifyContent:'center'}}><Icon name={icon} color={colors.green} size={21}/></View><View style={{flex:1}}><Label style={{fontSize:12,color:colors.muted}}>{title}</Label><Heading size={typeof value==='string'&&value.length>10?17:24}>{value}</Heading></View></View>{children}</Card>;}
export function ThemeSelector({theme,onSelect}:{theme:AppTheme;onSelect:(value:AppTheme)=>void}){const [extra,setExtra]=useState(theme==='lilac'||theme==='night');const options=[themeOptions[0],themeOptions[2],themeOptions[1],...(extra?themeOptions.slice(3):[])];return <>{options.map(option=><Pressable key={option.key} accessibilityRole="radio" accessibilityState={{checked:theme===option.key}} onPress={()=>onSelect(option.key)} style={{backgroundColor:colors.paper,borderRadius:20,borderWidth:theme===option.key?1.5:1,borderColor:theme===option.key?colors.green:colors.line,marginBottom:12,padding:8,flexDirection:'row',alignItems:'center',gap:16}}><Image source={themeArt[option.key]} style={{width:'42%',height:105,borderRadius:14}}/><View style={{flex:1}}><Heading size={21}>{option.name}</Heading><Label style={{fontSize:13,color:colors.muted,marginTop:5}}>{option.description}</Label></View><Icon name={theme===option.key?'check-circle':'circle-outline'} size={26} color={theme===option.key?colors.green:colors.mutedLight}/></Pressable>)}<Button small secondary onPress={()=>setExtra(!extra)}>{extra?'Réduire':'Autres thèmes existants'}</Button></>;}
export function AccentSelector({value,onSelect}:{value:AccentName;onSelect:(value:AccentName)=>void}){return <View style={{flexDirection:'row',gap:8}}>{(Object.keys(accents) as AccentName[]).map(key=><Pressable key={key} accessibilityRole="radio" accessibilityLabel={`Accent ${accents[key].label}`} accessibilityState={{checked:key===value}} onPress={()=>onSelect(key)} style={{flex:1,alignItems:'center',minHeight:90,gap:8,paddingVertical:5}}><View style={{padding:3,borderRadius:32,borderWidth:key===value?2:1,borderColor:key===value?colors.green:colors.line}}><View style={{width:48,height:48,borderRadius:24,backgroundColor:accents[key].swatch}}/></View><Label style={{fontSize:12,color:key===value?colors.green:colors.muted}}>{accents[key].label}</Label></Pressable>)}</View>;}
