import {ProfileHeaderButton} from './ProfileHeaderButton';
import React from 'react';
import {ImageBackground,Platform,Pressable,View} from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import Svg,{Circle} from 'react-native-svg';
import {AppTheme} from '../core/program';
import {colors,Label} from './theme';
export const themeArt={classic:require('../../assets/themes/emerald.png'),feminine:require('../../assets/themes/rose.png'),lilac:require('../../assets/themes/lilac.png'),night:require('../../assets/themes/night.png')};
export type IconName=React.ComponentProps<typeof MaterialCommunityIcons>['name'];
export function Icon({name,size=24,color=colors.gold}:{name:IconName;size?:number;color?:string}){return <MaterialCommunityIcons name={name} size={size} color={color} accessible={false} />;}
export const premiumShadow={shadowColor:'#352552',shadowOpacity:0.07,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2};
export function IslamicHero({title,subtitle,theme='lilac',children,compact=false}:{title:string;subtitle:string;theme?:AppTheme;children?:React.ReactNode;compact?:boolean}){return <ImageBackground source={themeArt[theme]} resizeMode="cover" imageStyle={{opacity:compact?0.12:0.42}} style={{marginHorizontal:-18,paddingHorizontal:24,paddingTop:compact?18:30,paddingBottom:compact?22:58,minHeight:compact?115:215,backgroundColor:colors.cream,overflow:'hidden'}}><View style={{backgroundColor:colors.cream+'C9',alignSelf:'flex-start',borderRadius:14,padding:8,maxWidth:'100%'}}><Label style={{fontSize:compact?29:30,fontWeight:'800',color:colors.green,lineHeight:38}}>{title}</Label><Label style={{color:colors.muted,fontSize:15,lineHeight:23,marginTop:5}}>{subtitle}</Label></View>{children}</ImageBackground>;}
export function ProgressTrack({value}:{value:number}){return <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:100,now:Math.round(value*100)}} style={{height:6,backgroundColor:colors.soft,borderRadius:8,overflow:'hidden'}}><View style={{height:6,width:`${Math.min(100,Math.max(0,value*100))}%`,backgroundColor:colors.green2,borderRadius:8}} /></View>;}
export function ProgressRing({value,size=130,children,strokeColor=colors.green2}:{value:number;size?:number;children?:React.ReactNode;strokeColor?:string}){const r=(size-12)/2,c=2*Math.PI*r;return <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:100,now:Math.round(value*100)}} style={{width:size,height:size,alignItems:'center',justifyContent:'center'}}><Svg width={size} height={size} style={{position:'absolute'}}><Circle cx={size/2} cy={size/2} r={r} fill={colors.paper} stroke={colors.soft} strokeWidth={9}/><Circle cx={size/2} cy={size/2} r={r} fill="none" stroke={strokeColor} strokeWidth={9} strokeDasharray={`${c*Math.min(1,Math.max(0,value))} ${c}`} strokeLinecap="round" rotation={-90} origin={`${size/2},${size/2}`} /></Svg>{children}</View>;}
export function GoldIcon({name,size=28}:{name:IconName;size?:number}){return <View style={{width:size+24,height:size+24,borderRadius:(size+24)/2,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center',...premiumShadow}}><Icon name={name} size={size} /></View>;}
export function SessionToolbar({onRecord,onAudio,onTranslation,onOptions,onBookmark,reading=false,active}:{onRecord:()=>void;onAudio:()=>void;onTranslation:()=>void;onOptions:()=>void;onBookmark?:()=>void;reading?:boolean;active?:'audio'|'record'|'translation'|'bookmark'|'options'|null}){
 const actions:[IconName,string,()=>void,string][]=reading?[['play','Écouter',onAudio,'audio'],['book-open-outline','Traduction',onTranslation,'translation'],['bookmark','Marque-page',onBookmark??(()=>{}),'bookmark'],['dots-horizontal','Plus d’options',onOptions,'options']]:[['microphone','Enregistrer\nma voix',onRecord,'record'],['play','Écouter\nun récitateur',onAudio,'audio'],['book-open-outline','Traduction',onTranslation,'translation'],['dots-horizontal','Plus d’options',onOptions,'options']];
 return <View style={{flexDirection:'row',backgroundColor:colors.paper,borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderColor:colors.line,paddingVertical:8,paddingHorizontal:5,...premiumShadow}}>{actions.map(([name,label,action,key],i)=>{const selected=active===key||(!active&&i===0);return <Pressable key={name} accessibilityRole="button" accessibilityState={{selected:active===key}} accessibilityLabel={label.replace('\n',' ')} onPress={action} style={{flex:1,minHeight:72,alignItems:'center',paddingHorizontal:2}}><View style={{height:40,width:40,borderRadius:20,backgroundColor:selected?colors.green:colors.soft,alignItems:'center',justifyContent:'center'}}><Icon name={name} color={selected?'white':colors.green}/></View><Label style={{fontSize:11,lineHeight:15,textAlign:'center',color:colors.green,marginTop:5}}>{label}</Label></Pressable>;})}</View>;
}

export const mainTabs=['Accueil','Coran','Programme','Progrès','Amis'] as const;
export function AppTopNavigation({tab,onTab,firstName,onProfile,onSettings,title='Apprendre le Coran',showTabs=true,onBack}:{tab:string;onTab:(tab:typeof mainTabs[number])=>void;firstName?:string;onProfile:()=>void;onSettings:()=>void;title?:string;showTabs?:boolean;onBack?:()=>void}){return <View style={{backgroundColor:colors.paper,borderBottomWidth:1,borderColor:colors.line}}><View style={{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingVertical:7,gap:5}}>{onBack&&<Pressable accessibilityLabel="Retour" onPress={onBack} style={{width:32,height:44,justifyContent:'center'}}><Icon name="chevron-left" color={colors.green}/></Pressable>}<Label style={{flex:1,fontSize:20,fontWeight:'800',color:colors.green}}>{title}</Label><ProfileHeaderButton firstName={firstName} onPress={onProfile}/><Pressable accessibilityLabel="Ouvrir les réglages" onPress={onSettings} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Icon name="cog-outline" color={colors.green}/></Pressable></View>{showTabs&&<View style={{flexDirection:'row'}}>{mainTabs.map(name=><Pressable key={name} accessibilityRole="tab" accessibilityState={{selected:tab===name}} onPress={()=>onTab(name)} style={{flex:1,minHeight:44,alignItems:'center',justifyContent:'center',borderBottomWidth:tab===name?3:0,borderColor:colors.green}}><Label style={{fontSize:13,fontWeight:tab===name?'800':'500',color:tab===name?colors.green:colors.muted}}>{name}</Label></Pressable>)}</View>}</View>;}
