import React,{useEffect,useState} from 'react';
import {FlatList,Linking,Pressable,ScrollView,View} from 'react-native';
import {Button,Card,CheckChoice,colors,Label} from './theme';
import {ArabicLabel,Heading,IconButton,SectionHeader,SegmentedControl} from './DesignSystem';
import {Icon,IconName} from './Premium';
import {FriendAvatar} from './FriendAvatar';
import {challengeStatus,DailyResponse,quizDay,QuizChallenge,QuizQuestion,quizStatistics} from '../core/quiz';
import {answerChallenge,answerDaily,createQuizChallenge,refreshQuiz,useQuiz,quizRpc} from '../services/quiz';
import {cachedFriendsSnapshot,FriendLink,listFriendLinks} from '../services/social';
const message=(e:unknown)=>e instanceof Error?e.message:'Connexion nécessaire. Réessaie.';
export function QuizHomeCards({userId,onQuiz,onFriends}:{userId?:string;onQuiz:()=>void;onFriends:()=>void}){
 const data=useQuiz(userId),done=data.responses.some(r=>r.day===quizDay()),available=data.day===quizDay()&&!!data.daily;
 return <View style={{flexDirection:'row',gap:10,marginBottom:12}}>{[{title:'Quiz',sub:done?'Question du jour terminée':available?'Question du jour disponible':'Question du jour',detail:done?'1/1 aujourd’hui':'Teste tes connaissances',icon:'trophy-outline' as IconName,color:colors.gold,onPress:onQuiz},{title:'Amis',sub:'Défie tes amis',detail:'Quiz entre amis',icon:'account-group-outline' as IconName,color:colors.review,onPress:onFriends}].map(item=><Pressable key={item.title} accessibilityRole="button" accessibilityLabel={item.title} onPress={item.onPress} style={{flex:1,minHeight:92,borderWidth:1,borderColor:colors.line,borderRadius:18,backgroundColor:colors.paper,padding:10,flexDirection:'row',gap:8}}><View style={{width:34,height:34,borderRadius:17,backgroundColor:item.color+'12',alignItems:'center',justifyContent:'center'}}><Icon name={item.icon} size={23} color={item.color}/></View><View style={{flex:1}}><Label style={{fontSize:16,fontWeight:'700',color:item.color}}>{item.title}</Label><Label style={{fontSize:11,marginTop:5}}>{item.sub}</Label><Label style={{fontSize:10,color:colors.muted,marginTop:4}}>{item.detail}</Label></View>{item.title==='Quiz'&&available&&!done&&<View style={{position:'absolute',right:9,top:9,width:6,height:6,borderRadius:3,backgroundColor:colors.red}}/>}</Pressable>)}</View>;
}
export function QuizStats({userId}:{userId?:string}){const s=quizStatistics(useQuiz(userId),userId??'');return <Card><Heading size={19}>Quiz</Heading><Label style={{fontSize:13,marginTop:7}}>Questions du jour · {s.correct} bonnes réponses / {s.total}</Label><Label style={{fontSize:12,color:colors.muted,marginTop:5}}>Taux de réussite · {s.rate} %</Label><Label style={{fontSize:12,marginTop:8}}>Défis · {s.played} joués · {s.wins} victoires · {s.ties} égalités</Label></Card>;}
function Answers({question,selected,onSelect,disabled=false}:{question:QuizQuestion;selected?:string;onSelect?:(id:string)=>void;disabled?:boolean}){const correction=!!selected&&!!question.correctAnswerId;return <View style={{gap:7,marginTop:12}}>{question.answers.map((a,i)=>{const good=correction&&a.id===question.correctAnswerId,bad=correction&&a.id===selected&&!good,color=good?colors.review:bad?colors.red:colors.muted;return <Pressable key={a.id} accessibilityRole="button" accessibilityLabel={`${String.fromCharCode(65+i)}. ${a.text}${a.id===selected?' · réponse choisie':''}`} accessibilityState={{disabled:disabled||!!selected,selected:a.id===selected}} disabled={disabled||!!selected} onPress={()=>onSelect?.(a.id)} style={{minHeight:48,borderRadius:13,borderWidth:1,borderColor:good||bad?color:colors.line,backgroundColor:good?colors.reviewSoft:bad?colors.red+'0C':a.id===selected?colors.selected:colors.paper,padding:10,flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:25,height:25,borderRadius:13,backgroundColor:good||bad?color:colors.surfaceSecondary,alignItems:'center',justifyContent:'center'}}><Label style={{fontSize:12,color:good||bad?'#FFFFFF':colors.muted}}>{String.fromCharCode(65+i)}</Label></View><Label style={{flex:1,fontSize:14,color:good||bad?color:colors.text}}>{a.text}</Label>{(good||bad)&&<Icon name={good?'check-circle':'close-circle'} size={20} color={color}/>}</Pressable>;})}</View>;}
function Correction({question,correct}:{question:QuizQuestion;correct:boolean}){return <Card style={{backgroundColor:colors.reviewSoft,marginTop:13}}><Heading size={18}>{correct?'Bonne réponse !':'Voici la bonne réponse'}</Heading>{!!question.explanation&&<Label style={{fontSize:14,marginTop:8}}>{question.explanation}</Label>}{!!question.arabic&&<ArabicLabel>{question.arabic}</ArabicLabel>}{!!question.translation&&<Label style={{fontSize:13,marginTop:6}}>{question.translation}</Label>}<Label style={{fontSize:12,color:colors.muted,marginTop:8}}>{[question.sourceTitle,question.sourceReference].filter(Boolean).join(' · ')}</Label>{question.sourceUrl?.startsWith('https://')&&<Button small secondary onPress={()=>void Linking.openURL(question.sourceUrl!)}>Voir la source</Button>}</Card>;}
function ChallengeRow({challenge,userId,onPress}:{challenge:QuizChallenge;userId:string;onPress:()=>void}){const own=challenge.creatorId===userId,name=own?challenge.opponentName:challenge.creatorName,status=challengeStatus(challenge,userId),remaining=Math.max(0,Math.ceil((Date.parse(challenge.expiresAt)-Date.now())/3600000));return <Pressable accessibilityRole="button" onPress={onPress}><Card style={{flexDirection:'row',alignItems:'center',gap:10,padding:12,marginBottom:7}}><FriendAvatar name={name} path={own?challenge.opponentAvatar:challenge.creatorAvatar}/><View style={{flex:1}}><Label style={{fontSize:15,fontWeight:'600'}}>{name}</Label><Label style={{fontSize:12,color:status==='À toi de jouer'?colors.green:colors.muted,marginTop:4}}>{status}</Label></View><Label style={{fontSize:11,color:colors.muted}}>{status==='Terminé'?`${challenge.answers.filter(a=>a.userId===userId&&a.isCorrect).length}/${challenge.questionCount} contre ${challenge.answers.filter(a=>a.userId!==userId&&a.isCorrect).length}/${challenge.questionCount}`:status==='Expiré'?'':`${remaining} h`}</Label><Icon name="chevron-right" size={20} color={colors.muted}/></Card></Pressable>;}
export function QuizScreen({userId,onClose,initialFriend,initialChallenge}:{userId?:string;onClose:()=>void;initialFriend?:string;initialChallenge?:string}){
 const data=useQuiz(userId),[view,setView]=useState<'home'|'daily'|'history'|'challenges'|'create'|'challenge'>(initialFriend?'create':initialChallenge?'challenge':'home'),[friendId,setFriendId]=useState(initialFriend??''),[challengeId,setChallengeId]=useState(initialChallenge??''),[quizSet,setQuizSet]=useState(''),[count,setCount]=useState<5|10>(10),[friends,setFriends]=useState<FriendLink[]>(()=>cachedFriendsSnapshot(userId??null)?.links.filter(l=>l.status==='accepted')??[]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[historyId,setHistoryId]=useState<string|null>(null);
 useEffect(()=>{void refreshQuiz().catch(e=>setNotice(message(e)));},[userId]);
 useEffect(()=>{if(view==='create'&&userId)void listFriendLinks(userId).then(l=>setFriends(l.filter(x=>x.status==='accepted'))).catch(()=>setNotice('Connexion nécessaire pour actualiser les amis.'));},[view,userId]);
 const day=quizDay(),response=historyId?data.responses.find(r=>r.day===historyId):data.responses.find(r=>r.day===day),daily=response?.question??(data.day===day?data.daily:null),challenge=data.challenges.find(c=>c.id===challengeId),own=challenge?.answers.filter(a=>a.userId===userId)??[],next=challenge?.questions.find(q=>!own.some(a=>a.questionId===q.id)),status=challenge?challengeStatus(challenge,userId??''):null;
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(message(e));}finally{setBusy(false);}};
 const back=()=>{setNotice('');if(view==='home')onClose();else if(view==='challenge')setView('challenges');else{setHistoryId(null);setView('home');}};
 const header=<><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12}}><IconButton name="chevron-left" label="Retour" onPress={back}/><Heading size={21}>{view==='daily'?'Question du jour':view==='history'?'Historique':view==='create'?'Nouveau défi':view==='challenge'?'Défi entre amis':'Quiz'}</Heading><IconButton name="chart-bar" label="Historique Quiz" onPress={()=>setView('history')}/></View>{!!notice&&<Card><Label style={{fontSize:12,color:colors.muted}}>{notice}</Label><Button small secondary onPress={()=>void act(refreshQuiz)}>Actualiser</Button></Card>}{!userId&&<Label style={{fontSize:13,color:colors.muted}}>Connecte-toi pour participer au Quiz.</Label>}</>;
 const openChallenge=(c:QuizChallenge)=>{setChallengeId(c.id);setView('challenge');};
 if(view==='history')return <FlatList data={data.responses} keyExtractor={r=>r.day} contentContainerStyle={{padding:18,paddingBottom:30}} ListHeaderComponent={header} ListEmptyComponent={<Label>Aucune réponse enregistrée.</Label>} renderItem={({item:r})=><Pressable accessibilityRole="button" onPress={()=>{setHistoryId(r.day);setView('daily');}}><Card><Label>{r.day===day?'Aujourd’hui':new Date(r.day+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</Label><Label style={{fontSize:12,color:r.pending?colors.muted:r.isCorrect?colors.review:colors.red,marginTop:5}}>{r.pending?'Synchronisation en attente':r.isCorrect?'✓ Bonne réponse':'✕ Mauvaise réponse'}</Label></Card></Pressable>}/>;
 if(view==='challenges')return <FlatList data={data.challenges} keyExtractor={c=>c.id} contentContainerStyle={{padding:18,paddingBottom:30}} ListHeaderComponent={<>{header}<Button onPress={()=>setView('create')}>Nouveau défi</Button><Label style={{fontSize:12,color:colors.muted,marginVertical:8}}>5 ou 10 questions · 48 heures</Label></>} ListEmptyComponent={<Label>Aucun défi pour le moment.</Label>} renderItem={({item})=><ChallengeRow challenge={item} userId={userId??''} onPress={()=>openChallenge(item)}/>}/>;
 return <ScrollView contentContainerStyle={{padding:18,paddingBottom:30}}>{header}
 {view==='home'&&<><View style={{alignItems:'center',paddingVertical:12}}><Icon name="trophy" size={42} color={colors.gold}/><Heading size={23}>Teste tes connaissances</Heading><Label style={{fontSize:12,color:colors.muted,textAlign:'center',marginTop:4}}>Coran, Tajwid, Prophètes, Sîra et plus encore</Label></View><Pressable accessibilityRole="button" accessibilityLabel="Question du jour" onPress={()=>{setHistoryId(null);setView('daily');}}><Card style={{backgroundColor:colors.gold+'12',borderColor:colors.gold+'35',padding:17,flexDirection:'row',gap:13,alignItems:'center'}}><Icon name="weather-sunny" size={34} color={colors.gold}/><View style={{flex:1}}><Heading size={19}>Question du jour</Heading><Label style={{fontSize:13,color:colors.muted,marginTop:5}}>Une nouvelle question chaque jour</Label><Label style={{fontSize:12,color:colors.review,marginTop:9}}>{response?'✓ Terminée aujourd’hui':daily?'● Disponible aujourd’hui':'Aucune question publiée aujourd’hui'}</Label></View><Icon name="chevron-right" color={colors.gold}/></Card></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Défis entre amis" onPress={()=>setView('challenges')}><Card style={{backgroundColor:colors.quizLavender,padding:17,flexDirection:'row',gap:13,alignItems:'center'}}><Icon name="account-group-outline" size={34} color={colors.quizPurple}/><View style={{flex:1}}><Heading size={19}>Défis entre amis</Heading><Label style={{fontSize:13,color:colors.muted,marginTop:5}}>Affronte tes amis sur 10 questions</Label><Label style={{fontSize:12,color:colors.quizPurple,marginTop:9}}>{data.challenges.filter(c=>!['Terminé','Expiré'].includes(challengeStatus(c,userId??''))).length} défis en cours</Label></View><Icon name="gamepad-variant-outline" color={colors.quizPurple}/></Card></Pressable><SectionHeader title="Mes défis" action="Voir tout" onPress={()=>setView('challenges')}/>{data.challenges.slice(0,3).map(c=><ChallengeRow key={c.id} challenge={c} userId={userId??''} onPress={()=>openChallenge(c)}/>)}{!data.challenges.length&&<Label style={{fontSize:13,color:colors.muted}}>Invite un ami à tester ses connaissances.</Label>}<Button secondary onPress={()=>setView('create')}>Nouveau défi</Button><Button secondary onPress={()=>setView('history')}>Historique</Button><CheckChoice label="Notifications Quiz" selected={data.notificationsEnabled!==false} onPress={()=>void act(async()=>{await quizRpc('quiz_set_notifications',{p_enabled:data.notificationsEnabled===false,p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await refreshQuiz();})}/></>}
 {view==='daily'&&(daily?<><Label style={{fontSize:12,color:colors.muted,marginBottom:10}}>{response?'✓ 1 / 1':'1 / 1'}</Label><Label style={{fontSize:11,color:colors.gold}}>{daily.category}</Label><Heading size={20}>{daily.question}</Heading><Answers question={daily} selected={response?.selectedAnswerId} disabled={!userId} onSelect={id=>{try{answerDaily(daily,id);}catch(e){setNotice(message(e));}}}/>{response?.pending?<Card><Label>Tes réponses ont été enregistrées.</Label><Label style={{fontSize:12,color:colors.muted,marginTop:6}}>La correction sera disponible après synchronisation.</Label></Card>:response&&<Correction question={daily} correct={!!response.isCorrect}/>}<Button secondary onPress={()=>setView('home')}>Retour au Quiz</Button></>:<Card><Label>Aucune question du jour disponible.</Label><Label style={{fontSize:12,color:colors.muted,marginTop:6}}>Les questions sont publiées par l’administrateur.</Label></Card>)}
 {view==='create'&&<><Heading size={19}>Choisir un ami</Heading>{friends.map(f=><Pressable key={f.id} accessibilityRole="radio" accessibilityState={{selected:friendId===f.other?.id}} onPress={()=>setFriendId(f.other?.id??'')}><Card style={{flexDirection:'row',alignItems:'center',gap:10,borderColor:friendId===f.other?.id?colors.green:colors.line}}><FriendAvatar name={f.other?.display_name??'Ami'} path={f.other?.avatar_path}/><Label style={{flex:1}}>{f.other?.display_name??'Ami'}</Label>{friendId===f.other?.id&&<Icon name="check-circle" color={colors.green}/>}</Card></Pressable>)}{!friends.length&&<Label style={{fontSize:13,color:colors.muted,marginVertical:12}}>Ajoute un ami dans l’espace Amis pour lancer un défi.</Label>}<Button secondary onPress={()=>setQuizSet('')}>Questions aléatoires{!quizSet?' ✓':''}</Button>{data.quizSets?.map(q=><Button key={q.id} secondary onPress={()=>{setQuizSet(q.id);setCount(10);}}>{q.title} · {q.category}{quizSet===q.id?' ✓':''}</Button>)}{!quizSet&&<SegmentedControl options={['5 questions','10 questions'] as const} value={count===5?'5 questions':'10 questions'} onChange={v=>setCount(v==='5 questions'?5:10)}/>}<Label style={{fontSize:12,color:colors.muted,marginVertical:10}}>Les mêmes questions pour vous deux · durée 48 heures</Label><Button disabled={busy||!friendId||!userId} onPress={()=>void act(async()=>{const id=await createQuizChallenge(friendId,count,quizSet||undefined);setChallengeId(id);setView('challenge');})}>{busy?'Création…':'Lancer le défi'}</Button></>}
 {view==='challenge'&&(challenge?<><Heading size={20}>{challenge.creatorName} · {challenge.opponentName}</Heading>{status==='Terminé'?<><Card><Heading size={22}>Défi terminé</Heading>{[challenge.creatorId,challenge.opponentId].map(id=><Label key={id} style={{fontSize:16,marginTop:8}}>{id===challenge.creatorId?challenge.creatorName:challenge.opponentName} · {challenge.answers.filter(a=>a.userId===id&&a.isCorrect).length} / {challenge.questionCount}</Label>)}<Heading size={18}>{(()=>{const a=challenge.answers.filter(x=>x.userId===challenge.creatorId&&x.isCorrect).length,b=challenge.answers.filter(x=>x.userId===challenge.opponentId&&x.isCorrect).length;return a===b?'Égalité':`${a>b?challenge.creatorName:challenge.opponentName} remporte le défi`;})()}</Heading></Card>{challenge.questions.map(q=>{const r=own.find(a=>a.questionId===q.id);return <View key={q.id}><Heading size={19}>{q.question}</Heading><Answers question={q} selected={r?.selectedAnswerId} disabled/><Correction question={q} correct={!!r?.isCorrect}/></View>;})}</>:status==='Expiré'?<Card><Heading size={20}>Défi expiré</Heading><Label>Aucun vainqueur n’est comptabilisé.</Label></Card>:next?<><Label style={{fontSize:12,color:colors.muted,marginVertical:10}}>{own.length+1} / {challenge.questionCount} · {Math.max(0,Math.ceil((Date.parse(challenge.expiresAt)-Date.now())/3600000))} h restantes</Label><Label style={{fontSize:11,color:colors.gold}}>{next.category}</Label><Heading size={20}>{next.question}</Heading><Answers question={next} disabled={busy} onSelect={answer=>void act(()=>answerChallenge(challenge.id,next.id,answer))}/><Label style={{fontSize:12,color:colors.muted,marginTop:12}}>La correction sera révélée quand vous aurez tous les deux terminé.</Label></>:<Card><Heading size={19}>Tes réponses ont été enregistrées</Heading><Label style={{marginTop:8}}>En attente de {challenge.creatorId===userId?challenge.opponentName:challenge.creatorName}</Label></Card>}</>:<Card><Label>Défi non disponible dans le cache.</Label><Button secondary onPress={()=>void act(refreshQuiz)}>Actualiser</Button></Card>)}
 </ScrollView>;
}
