import React,{useEffect,useMemo,useRef} from 'react';
import {Animated,PanResponder,Pressable,ScrollView,View} from 'react-native';
import {Icon,premiumShadow} from './Premium';
import {colors,Label} from './theme';
export function ReaderMoreSheet({bottom,onClose,onSurah,onTranslation,onAudio,onDisplay}:{bottom:number;onClose:()=>void;onSurah:()=>void;onTranslation:()=>void;onAudio:()=>void;onDisplay:()=>void}){
 const entrance=useRef(new Animated.Value(70)).current;
 useEffect(()=>{Animated.timing(entrance,{toValue:0,duration:220,useNativeDriver:true}).start();},[entrance]);
 const drag=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>g.dy>12&&Math.abs(g.dy)>Math.abs(g.dx),onPanResponderRelease:(_,g)=>{if(g.dy>45)onClose();}}),[onClose]);
 const rows=[{title:'Changer de sourate',subtitle:'Choisir une sourate ou aller à une page',icon:'book-open-variant' as const,bg:'#F2EEFB',badge:'#E4DAFF',color:'#7356AD',press:onSurah},{title:'Traduction française',subtitle:'Afficher / masquer la traduction',icon:'earth' as const,bg:'#EDF4FC',badge:'#D7E7FF',color:'#427FBC',press:onTranslation},{title:'Réglages audio',subtitle:'Récitateur, répétitions et vitesse',icon:'headphones' as const,bg:'#FFF0F4',badge:'#FFDFE8',color:'#BD5B7B',press:onAudio},{title:'Affichage du Coran',subtitle:'Choisir le style, la taille et les options',icon:'cog-outline' as const,bg:'#EEF8F5',badge:'#D7EEE6',color:'#478F7C',press:onDisplay}];
 return <><Pressable accessibilityRole="button" accessibilityLabel="Fermer les options" onPress={onClose} style={{position:'absolute',top:0,left:0,right:0,bottom,backgroundColor:'rgba(30,24,47,0.12)',zIndex:6}}/><Animated.View style={{position:'absolute',left:0,right:0,bottom,maxHeight:'75%',padding:14,borderTopLeftRadius:30,borderTopRightRadius:30,backgroundColor:colors.paper,...premiumShadow,elevation:12,zIndex:7,transform:[{translateY:entrance}]}}><View {...drag.panHandlers} style={{alignItems:'center',paddingVertical:6}}><View style={{width:36,height:4,borderRadius:4,backgroundColor:colors.softBorder}}/></View><View style={{flexDirection:'row',alignItems:'center',marginBottom:10}}><Label style={{flex:1,fontWeight:'800',fontSize:20}}>Plus d’options</Label><Pressable accessibilityRole="button" accessibilityLabel="Fermer le panneau" onPress={onClose} style={{width:44,height:44,borderRadius:22,backgroundColor:colors.soft,justifyContent:'center',alignItems:'center'}}><Icon name="close" color={colors.green}/></Pressable></View><ScrollView>{rows.map(row=><Pressable key={row.title} accessibilityRole="button" accessibilityLabel={row.title} onPress={row.press} style={({pressed})=>({minHeight:66,flexDirection:'row',alignItems:'center',gap:10,padding:10,marginBottom:8,borderRadius:18,borderWidth:1,borderColor:colors.line,backgroundColor:row.bg,opacity:pressed?0.72:1})}><View style={{width:40,height:40,borderRadius:13,backgroundColor:row.badge,alignItems:'center',justifyContent:'center'}}><Icon name={row.icon} size={23} color={row.color}/></View><View style={{flex:1}}><Label style={{fontSize:14,fontWeight:'700'}}>{row.title}</Label><Label style={{fontSize:11,color:colors.muted,marginTop:3}}>{row.subtitle}</Label></View><Icon name="chevron-right" size={20} color={colors.green2}/></Pressable>)}</ScrollView></Animated.View></>;
}
