import React from 'react';
import { Pressable, StyleSheet, Text, TextInput, View, ViewStyle } from 'react-native';

export const colors={green:'#153F36',green2:'#276454',cream:'#F7F5EE',paper:'#FFFDF7',beige:'#E9E2D2',gold:'#B39559',text:'#20342E',muted:'#6C7B72',line:'#E4E7DF',red:'#9D554D'};
export function Label({children,style}:{children:React.ReactNode;style?:any}){return <Text style={[{color:colors.text,fontSize:16},style]}>{children}</Text>}
export function Title({children}:{children:React.ReactNode}){return <Text style={{fontSize:30,fontWeight:'700',color:colors.green,letterSpacing:-0.5}}>{children}</Text>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[styles.card,style]}>{children}</View>}
export function Button({children,onPress,secondary=false,disabled=false,small=false}:{children:React.ReactNode;onPress:()=>void;secondary?:boolean;disabled?:boolean;small?:boolean}){return <Pressable onPress={onPress} disabled={disabled} style={[styles.button,secondary&&styles.buttonSecondary,small&&{paddingVertical:10,paddingHorizontal:14},disabled&&{opacity:0.45}]}><Text style={[{color:secondary?colors.green:'#FFFFFF',fontSize:small?13:15,fontWeight:'700',textAlign:'center'},secondary&&{color:colors.green}]}>{children}</Text></Pressable>}
export function Choice({label,selected,onPress,subtitle}:{label:string;selected:boolean;onPress:()=>void;subtitle?:string}){return <Pressable onPress={onPress} style={[styles.choice,selected&&styles.choiceSelected]}><View style={{flex:1}}><Label style={{fontWeight:selected?'700':'500'}}>{label}</Label>{subtitle&&<Label style={{fontSize:12,color:colors.muted,marginTop:3}}>{subtitle}</Label>}</View><Text style={{color:selected?colors.green:colors.muted,fontSize:21}}>{selected?'●':'○'}</Text></Pressable>}
export function CheckChoice({label,selected,onPress,subtitle}:{label:string;selected:boolean;onPress:()=>void;subtitle?:string}){return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={[styles.choice,selected&&styles.choiceSelected]}><View style={{flex:1}}><Label style={{fontWeight:selected?'700':'500'}}>{label}</Label>{subtitle&&<Label style={{fontSize:12,color:colors.muted,marginTop:3}}>{subtitle}</Label>}</View><View style={{width:24,height:24,borderRadius:6,borderWidth:1,borderColor:selected?colors.green:colors.muted,backgroundColor:selected?colors.green:'transparent',alignItems:'center',justifyContent:'center'}}><Text style={{color:'white',fontWeight:'700'}}>{selected?'✓':''}</Text></View></Pressable>}
export function Field({value,onChangeText,placeholder,keyboardType,secureTextEntry}:{value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:any;secureTextEntry?:boolean}){return <TextInput style={styles.field} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#98A49B" keyboardType={keyboardType} secureTextEntry={secureTextEntry} autoCapitalize="none" />}
export const styles=StyleSheet.create({card:{backgroundColor:colors.paper,borderRadius:22,padding:18,borderWidth:1,borderColor:colors.line,marginBottom:14},button:{backgroundColor:colors.green,borderRadius:15,paddingVertical:15,paddingHorizontal:18,alignItems:'center',justifyContent:'center',marginVertical:5},buttonSecondary:{backgroundColor:'#ECF1EA',borderWidth:1,borderColor:'#CAD8CE'},choice:{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:colors.line,borderRadius:14,padding:13,marginBottom:8,backgroundColor:colors.paper},choiceSelected:{borderColor:colors.green2,backgroundColor:'#EAF2EC'},field:{borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,paddingVertical:12,backgroundColor:colors.paper,color:colors.text,fontSize:16,marginBottom:8}});
