import React from 'react';
import { Pressable, Text, TextInput, View, ViewStyle } from 'react-native';
import { AppTheme } from '../core/program';

const palettes={
  classic:{green:'#153F36',green2:'#276454',cream:'#F7F5EE',paper:'#FFFDF7',beige:'#E9E2D2',gold:'#B39559',text:'#20342E',muted:'#6C7B72',line:'#E4E7DF',red:'#9D554D',soft:'#ECF1EA',softBorder:'#CAD8CE',selected:'#EAF2EC',onDark:'#BFD6C9',onDarkSoft:'#C9DDCF',track:'#49756B',progress:'#DBC591',surahBadge:'#E8EFE8'},
  feminine:{green:'#9D496B',green2:'#C76D91',cream:'#FFFAFC',paper:'#FFF5F8',beige:'#F3DCE5',gold:'#B39559',text:'#3C2833',muted:'#765B69',line:'#EBCAD8',red:'#9D554D',soft:'#F3DCE5',softBorder:'#DCA6BD',selected:'#F8E7EE',onDark:'#FBE4ED',onDarkSoft:'#F5D8E4',track:'#B9708D',progress:'#F3DCE5',surahBadge:'#F3DCE5'}
};
export const colors={...palettes.classic};
export function applyTheme(theme:AppTheme){Object.assign(colors,palettes[theme]);}
export function Label({children,style}:{children:React.ReactNode;style?:any}){return <Text style={[{color:colors.text,fontSize:16},style]}>{children}</Text>}
export function Title({children}:{children:React.ReactNode}){return <Text style={{fontSize:30,fontWeight:'700',color:colors.green,letterSpacing:-0.5}}>{children}</Text>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[{backgroundColor:colors.paper,borderRadius:22,padding:18,borderWidth:1,borderColor:colors.line,marginBottom:14},style]}>{children}</View>}
export function Button({children,onPress,secondary=false,disabled=false,small=false}:{children:React.ReactNode;onPress:()=>void;secondary?:boolean;disabled?:boolean;small?:boolean}){return <Pressable onPress={onPress} disabled={disabled} style={[{backgroundColor:secondary?colors.soft:colors.green,borderRadius:15,paddingVertical:small?10:15,paddingHorizontal:small?14:18,alignItems:'center',justifyContent:'center',marginVertical:5,borderWidth:secondary?1:0,borderColor:colors.softBorder},disabled&&{opacity:0.45}]}><Text style={{color:secondary?colors.green:'#FFFFFF',fontSize:small?13:15,fontWeight:'700',textAlign:'center'}}>{children}</Text></Pressable>}
export function Choice({label,selected,onPress,subtitle}:{label:string;selected:boolean;onPress:()=>void;subtitle?:string}){return <Pressable onPress={onPress} style={{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:selected?colors.green2:colors.line,borderRadius:14,padding:13,marginBottom:8,backgroundColor:selected?colors.selected:colors.paper}}><View style={{flex:1}}><Label style={{fontWeight:selected?'700':'500'}}>{label}</Label>{subtitle&&<Label style={{fontSize:12,color:colors.muted,marginTop:3}}>{subtitle}</Label>}</View><Text style={{color:selected?colors.green2:colors.muted,fontSize:21}}>{selected?'●':'○'}</Text></Pressable>}
export function CheckChoice({label,selected,onPress,subtitle}:{label:string;selected:boolean;onPress:()=>void;subtitle?:string}){const pink='#C76D91';return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:selected?pink:colors.line,borderRadius:14,padding:13,marginBottom:8,backgroundColor:selected?'#FFF0F5':colors.paper}}><View style={{width:24,height:24,borderRadius:4,borderWidth:2,borderColor:selected?pink:colors.muted,backgroundColor:selected?pink:'transparent',alignItems:'center',justifyContent:'center'}}><Text style={{color:'white',fontWeight:'700'}}>{selected?'✓':''}</Text></View><View style={{flex:1}}><Label style={{fontWeight:selected?'700':'500'}}>{label}</Label>{subtitle&&<Label style={{fontSize:12,color:colors.muted,marginTop:3}}>{subtitle}</Label>}</View></Pressable>}
export function Field({value,onChangeText,placeholder,keyboardType,secureTextEntry,autoCapitalize='none'}:{value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:any;secureTextEntry?:boolean;autoCapitalize?:'none'|'sentences'|'words'|'characters'}){return <TextInput style={{borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,paddingVertical:12,backgroundColor:colors.paper,color:colors.text,fontSize:16,marginBottom:8}} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType} secureTextEntry={secureTextEntry} autoCapitalize={autoCapitalize} />}
