"""Import only independent Quran resources from a rights-cleared IPA.

Requires fonttools and brotli. No app executable, credentials or audio are copied.
Usage: python scripts/import-coran-test.py source.ipa
"""
import gzip, hashlib, io, json, pathlib, sys, zipfile
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = 'Payload/Runner.app/Frameworks/App.framework/flutter_assets/packages/quran_library/assets/'
OUT = ROOT / 'assets/coran-test'
DATA = ROOT / 'src/coranTest/data'
OUT.mkdir(parents=True, exist_ok=True)
DATA.mkdir(parents=True, exist_ok=True)

def write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')

with zipfile.ZipFile(sys.argv[1]) as archive:
    read_json = lambda name: json.loads(gzip.decompress(archive.read(BASE + 'jsons/' + name + '.json.gz')))
    words = {int(w['id']): w for w in read_json('qpc-v4').values()}
    arabic = {int(w['id']): w['text'] for w in read_json('qpc-hafs-word-by-word').values()}
    lines = read_json('qpc_v4_ayah_info')
    quran = read_json('quranV4')['data']['surahs']
    verse_meta = {f"{s['number']}:{a['numberInSurah']}": a for s in quran for a in s['ayahs']}
    provenance = {}
    page_modules, font_modules, index = [], [], {}
    for page in range(1, 605):
        name = f'fonts/quran_fonts_qfc4/QCF4{page:03}_COLOR-Regular.ttf.gz'
        original = archive.read(BASE + name)
        font = TTFont(io.BytesIO(gzip.decompress(original)))
        cmap = font.getBestCmap()
        units = font['head'].unitsPerEm
        blocks = []
        max_advance = 0
        for row in (r for r in lines if r['page_number'] == page):
            block = {'line': row['line_number'], 'type': row['line_type'], 'centered': bool(row['is_centered']), 'surah': row['surah_number'] or None, 'words': []}
            if row['line_type'] == 'ayah':
                advance = 0
                for word_id in range(int(row['first_word_id']), int(row['last_word_id']) + 1):
                    w = words[word_id]
                    key = f"{w['surah']}:{w['ayah']}"
                    for char in w['text']:
                        assert ord(char) in cmap, (page, word_id, ord(char))
                        advance += font['hmtx'][cmap[ord(char)]][0]
                    block['words'].append([word_id, int(w['surah']), int(w['ayah']), int(w['word']), w['text'], arabic[word_id]])
                    entry = index.setdefault(key, {'id': verse_meta[key]['number'], 'pages': [], 'lines': []})
                    if page not in entry['pages']: entry['pages'].append(page)
                    if [page, row['line_number']] not in entry['lines']: entry['lines'].append([page, row['line_number']])
                max_advance = max(max_advance, advance)
            blocks.append(block)
        first = next(w for b in blocks for w in b['words'])
        meta = verse_meta[f'{first[1]}:{first[2]}']
        # A single scale per page preserves every glyph's original proportions.
        size = min(70, 940 * units / max_advance)
        write_json(DATA / f'{page}.json', {'page': page, 'surah': first[1], 'juz': meta['juz'], 'fontSize': size, 'lines': blocks})
        font.flavor = 'woff2'
        font.save(OUT / f'{page}.woff2')
        provenance[name] = hashlib.sha256(original).hexdigest()
        page_modules.append(f"  {page}:()=>require('./data/{page}.json'),")
        font_modules.append(f"  {page}:require('../../assets/coran-test/{page}.woff2'),")
    for name in ['surah-name-v4', 'UthmanicHafs_V20', 'vertopal.com_QCF_Bismillah-Regular']:
        font = TTFont(io.BytesIO(archive.read(BASE + f'fonts/{name}.ttf')))
        font.flavor = 'woff2'
        font.save(OUT / f'{name}.woff2')
    banner=next(n for n in archive.namelist() if n.startswith(BASE) and n.endswith('/surahSvgBanner.svg'))
    write_json(DATA / 'ornament.json', archive.read(banner).decode('utf-8'))
    write_json(DATA / 'verse-index.json', index)
    write_json(OUT / 'provenance.json', {'source': pathlib.Path(sys.argv[1]).name, 'sha256': hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest(), 'fontFormat': 'lossless WOFF2 / COLR + CPAL preserved', 'resources': provenance})
    (ROOT / 'src/coranTest/resources.ts').write_text("// Generated by scripts/import-coran-test.py; static Metro asset references.\nexport const testPages:Record<number,()=>unknown>={\n" + '\n'.join(page_modules) + "\n};\nexport const testFonts:Record<number,number>={\n" + '\n'.join(font_modules) + "\n};\nexport const titleFont=require('../../assets/coran-test/surah-name-v4.woff2');\nexport const arabicFont=require('../../assets/coran-test/UthmanicHafs_V20.woff2');\nexport const basmalaFont=require('../../assets/coran-test/vertopal.com_QCF_Bismillah-Regular.woff2');\n", encoding='utf-8')
print('Imported 604 pages, 604 color fonts,', len(index), 'verse mappings.')
