import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,Switch,View} from 'react-native';
import {Button,Card,colors,Field,Label,Title} from './ui/theme';
import {ContentCard,ContentTabs} from './DailyContentsScreen';
import * as service from './services/dailyContents';
import {isSocialAdmin} from './services/social';
const id=()=>'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return (c==='x'?r:(r&3)|8).toString(16);});
export function AdminDailyContents({onClose}:{onClose:()=>void}){
 const [chooseCategory,setChooseCategory]=useState(false);
 const [type,setType]=useState<service.ContentType>('invocation'),[cats,setCats]=useState<service.ContentCategory[]>([]),[items,setItems]=useState<service.DailyContent[]>([]),[dates,setDates]=useState<service.Schedule[]>([]),[edit,setEdit]=useState<service.DailyContent|null>(null),[category,setCategory]=useState<service.ContentCategory|null>(null),[manage,setManage]=useState(false),[preview,setPreview]=useState(false),[date,setDate]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const load=async(append=false)=>{if(!await isSocialAdmin())throw new Error('Accès administrateur refusé.');const next=append?offset+30:0;const [c,r,s]=await Promise.all([service.categories(true),service.contents(type,undefined,next,true),service.schedules()]);setCats(c);setItems(old=>append?[...old,...r]:r);setDates(s);setOffset(next);setMore(r.length===30);};
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load();setNotice('Enregistré.');}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 useEffect(()=>{load().catch(e=>setNotice(String(e)));},[type]);
 const update=(key:keyof service.DailyContent,value:any)=>setEdit(current=>current?{...current,[key]:value}:null);
 const save=()=>act(async()=>{if(!edit)return;if(!edit.category_id||!edit.french_text.trim()||!edit.source.trim()||edit.type==='invocation'&&(!edit.arabic_text?.trim()||!edit.phonetic_text?.trim()))throw new Error('Renseigne la catégorie et tous les champs obligatoires.');for(const url of [edit.audio_url,edit.image_url])if(url&&!/^https:\/\/\S+$/.test(url))throw new Error('Les fichiers doivent utiliser une URL HTTPS valide.');if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Date : AAAA-MM-JJ.');await service.saveContentAndSchedule(edit,date);setEdit(null);setPreview(false);});
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,paddingBottom:50}}><Button secondary onPress={onClose}>‹ Administration</Button><Title>Rappels & Invocations</Title>{!!notice&&<Card><Label>{notice}</Label></Card>}
 <ContentTabs type={type} onChange={t=>{setEdit(null);setType(t);}} />
 {edit?<><Button secondary onPress={()=>{setEdit(null);setPreview(false);}}>Annuler</Button>{preview?<ContentCard item={edit} preview />:<Card>
 <Label>Catégorie *</Label><Button small secondary onPress={()=>setChooseCategory(!chooseCategory)}>{cats.find(c=>c.id===edit.category_id)?.name??'Choisir une catégorie'} ⌄</Button>{chooseCategory&&cats.filter(c=>c.type===type).map(c=><Button key={c.id} small secondary={edit.category_id!==c.id} onPress={()=>{update('category_id',c.id);setChooseCategory(false);}}>{c.icon} {c.name}{c.is_active?'':' · inactive'}</Button>)}{!cats.some(c=>c.type===type)&&<><Label>Crée d’abord une catégorie pour ce type de contenu.</Label><Button secondary onPress={()=>{setEdit(null);setManage(true);}}>Gérer les catégories</Button></>}
 <Field placeholder="Titre (facultatif)" value={edit.title??''} onChangeText={v=>update('title',v||null)} />
 {type==='invocation'&&<><Label>Arabe *</Label><Field multiline placeholder="Texte arabe" value={edit.arabic_text??''} onChangeText={v=>update('arabic_text',v)} /><Field placeholder="Phonétique *" value={edit.phonetic_text??''} onChangeText={v=>update('phonetic_text',v)} /></>}
 <Field multiline placeholder={type==='invocation'?'Traduction française *':'Texte du rappel *'} value={edit.french_text} onChangeText={v=>update('french_text',v)} />
 {type==='reminder'&&<><Field multiline placeholder="Explication courte (facultative)" value={edit.explanation??''} onChangeText={v=>update('explanation',v||null)} /></>}
 <Field placeholder="Petite image : URL HTTPS (facultative)" value={edit.image_url??''} onChangeText={v=>update('image_url',v||null)} />
 <Field placeholder="Source fiable *" value={edit.source} onChangeText={v=>update('source',v)} /><Field placeholder="Référence (facultative)" value={edit.reference??''} onChangeText={v=>update('reference',v||null)} />
 <Field placeholder="Audio MP3/M4A/AAC : URL HTTPS (facultative)" value={edit.audio_url??''} onChangeText={v=>update('audio_url',v||null)} />
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Label>Actif</Label><Switch value={edit.is_active} onValueChange={v=>update('is_active',v)} /></View>
 <Label>Programmer comme contenu du jour (facultatif)</Label><Field placeholder="AAAA-MM-JJ" value={date} onChangeText={setDate} />
 </Card>}<Button secondary onPress={()=>setPreview(!preview)}>{preview?'Revenir au formulaire':'Aperçu'}</Button><Button disabled={busy} onPress={save}>{busy?'Enregistrement…':'Enregistrer'}</Button></>:<>
 <Button onPress={()=>{setDate('');setPreview(false);setEdit({id:id(),type,title:null,arabic_text:null,phonetic_text:null,french_text:'',explanation:null,source:'',reference:null,category_id:cats.find(c=>c.type===type&&c.is_active)?.id??'',audio_url:null,image_url:null,is_active:true});}}>+ Ajouter {type==='invocation'?'une invocation':'un rappel'}</Button>
 <Button secondary onPress={()=>setManage(!manage)}>Gérer les catégories</Button>
 {manage&&<Card><Button small onPress={()=>setCategory({id:id(),type,name:'',icon:'☾',display_order:cats.filter(c=>c.type===type).length,is_active:true})}>+ Ajouter une catégorie</Button>
 {category&&<><Field placeholder="Nom *" value={category.name} onChangeText={name=>setCategory({...category,name})} /><Field placeholder="Icône" value={category.icon} onChangeText={icon=>setCategory({...category,icon})} /><Field placeholder="Ordre (nombre)" keyboardType="numeric" value={String(category.display_order)} onChangeText={v=>setCategory({...category,display_order:Number(v)||0})} /><Label>Active</Label><Switch value={category.is_active} onValueChange={is_active=>setCategory({...category,is_active})} /><Button disabled={busy||!category.name.trim()} onPress={()=>act(async()=>{await service.saveCategory({...category,name:category.name.trim()});setCategory(null);})}>Enregistrer la catégorie</Button><Button secondary onPress={()=>setCategory(null)}>Annuler</Button></>}
 {cats.filter(c=>c.type===type).map(c=><View key={c.id}><Label>{c.icon} {c.name} · ordre {c.display_order} · {c.is_active?'active':'inactive'}</Label><Button small secondary onPress={()=>setCategory(c)}>Modifier</Button><Button small secondary onPress={()=>act(()=>service.saveCategory({...c,is_active:!c.is_active}))}>{c.is_active?'Désactiver':'Activer'}</Button><Button small secondary onPress={()=>Alert.alert('Supprimer cette catégorie ?','Une catégorie contenant des contenus ne peut pas être supprimée. Désactive-la pour la masquer.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>act(()=>service.deleteCategory(c.id))}])}>Supprimer</Button></View>)}</Card>}
 {items.map(item=><Card key={item.id}><Label style={{fontWeight:'700'}}>{item.title??item.french_text.slice(0,70)}</Label><Label>{cats.find(c=>c.id===item.category_id)?.name} · {item.is_active?'Actif':'Inactif'}</Label>{dates.filter(s=>s.content_id===item.id).map(s=><View key={s.display_date}><Label>Programmé le {s.display_date.split('-').reverse().join('/')}</Label><Button small secondary onPress={()=>act(()=>service.removeSchedule(s.type,s.display_date))}>Retirer cette programmation</Button></View>)}
 <Button small secondary onPress={()=>{setEdit(item);setPreview(false);setDate('');}}>Modifier / programmer</Button><Button small secondary onPress={()=>{setEdit(item);setPreview(true);setDate('');}}>Aperçu</Button><Button small secondary onPress={()=>act(()=>service.saveContent({...item,is_active:!item.is_active}))}>{item.is_active?'Désactiver':'Activer'}</Button><Button small secondary onPress={()=>Alert.alert(`Supprimer ${type==='invocation'?'cette invocation':'ce rappel'} ?`,'Le contenu et sa programmation seront supprimés.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>act(()=>service.deleteContent(item.id))}])}>Supprimer</Button></Card>)}
 {more&&<Button secondary disabled={busy} onPress={()=>load(true).catch(e=>setNotice(String(e)))}>Afficher la suite</Button>}
 </>}
 </ScrollView>;
}
