import React from 'react';
import {Alert,Pressable,ScrollView,View} from 'react-native';
import {AppState} from './core/program';
import {deleteBookmark,visibleBookmarks,VerseBookmark} from './core/bookmarks';
import {surahs,verseAt} from './core/quran';
import {Button,Card,colors,Label,Title} from './ui/theme';
import {Icon} from './ui/Premium';

export function BookmarksScreen({state,update,onResume,onClose,pageForBookmark}:{state:AppState;update:(state:AppState)=>void;onResume:(id:number)=>void;onClose:()=>void;pageForBookmark?:(item:VerseBookmark)=>number}){
 const items=visibleBookmarks(state),lastUsed=items.filter(b=>b.lastUsedAt).sort((a,b)=>b.lastUsedAt!.localeCompare(a.lastUsedAt!))[0]?.verseId;
 return <View style={{flex:1,backgroundColor:colors.cream}}><View style={{padding:16,flexDirection:'row',alignItems:'center',gap:8}}><Pressable accessibilityLabel="Retour à la lecture" onPress={onClose} style={{width:44,height:44,justifyContent:'center'}}><Icon name="chevron-left" color={colors.green}/></Pressable><View style={{flex:1}}><Title>Mes marques-pages</Title><Label style={{fontSize:12,color:colors.muted}}>Retrouve facilement tes passages enregistrés</Label></View></View><ScrollView contentContainerStyle={{padding:16,paddingBottom:30}}><Card style={{backgroundColor:colors.soft}}><Label>Chaque marque-page conserve le verset exact où reprendre ta lecture.</Label></Card>{!items.length&&<Card><Label>Aucun marque-page enregistré. Touche « Marque-page », puis un verset sur la page.</Label></Card>}{items.map(item=><Card key={item.verseId}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Icon name="bookmark" color={colors.green}/><View style={{flex:1}}><Label style={{fontWeight:'800',fontSize:18}}>{surahs[item.surah-1].name}</Label><Label style={{fontSize:12,color:colors.muted}}>Page {pageForBookmark?.(item)??item.page} · Verset {item.ayah}</Label></View><Pressable accessibilityLabel={`Supprimer le marque-page ${surahs[item.surah-1].name} verset ${item.ayah}`} onPress={()=>Alert.alert('Supprimer ce marque-page ?','Le verset restera disponible dans le Coran.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>update(deleteBookmark(state,item.verseId))}])} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Icon name="dots-vertical" color={colors.green}/></Pressable></View>{lastUsed===item.verseId&&<Label style={{color:colors.green,fontSize:11,marginTop:8}}>Dernière reprise</Label>}<Label numberOfLines={2} style={{textAlign:'right',writingDirection:'rtl',fontSize:23,lineHeight:42,marginTop:12}}>{verseAt(item.verseId).text}</Label><Button secondary onPress={()=>onResume(item.verseId)}>Reprendre</Button></Card>)}</ScrollView></View>;
}
