import {marginAnnotations} from './core/marginAnnotations';
import {isZipSource,zipPageData,zipPageRange} from './core/quranSources';
import {quranLineUri} from './services/quranDownload';
import madaniMarkers from './data/quran-tests/coran_1441-markers.json';

import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './ui/Premium';
import {GestureResponderEvent,Image,Pressable,Text,View} from 'react-native';
import {colors,Label} from './ui/theme';
import {mushafImages} from './data/mushafImages';
import boundsRaw from './data/bounds.json';
import {mushafTajweedImages} from './data/mushafTajweedImages';
import tajweedBoundsRaw from './data/mushaf-tajweed-bounds.json';
import tajweedDimensionsRaw from './data/mushaf-tajweed-dimensions.json';
import {frenchVerse,tajweedColor,tajweedSpans,verseAtImagePoint} from './core/readerData';
import {pageRange,Range,surahs,verseAt,verseId} from './core/quran';

type Props={marginGutter?:number;sessionThrough?:number;sessionColor?:string;studyBanner?:React.ReactNode;textScale?:number;mapImagePoint?:(event:GestureResponderEvent,callback:(x:number,y:number)=>void)=>void;allowTap?:()=>boolean;page:number;width:number;height:number;mode:'traditional'|'tajweed'|'tajweedPages'|'coran_1441';language:'ar'|'fr';playingVerseId:number|null;difficultyIds?:number[];sessionRange:Range;showSession:boolean;bookmarkIds?:number[];onVersePress?:(id:number)=>void;onVerseLongPress:(id:number)=>void;onBlankLongPress:()=>void;onTap:()=>void};
const bounds=boundsRaw as Record<string,number[][]>;

export function MushafPage({marginGutter=0,sessionThrough=0,sessionColor=colors.green,studyBanner,textScale=1,mapImagePoint,allowTap=()=>true,page,width,height,mode,language,playingVerseId,difficultyIds=[],bookmarkIds=[],onVersePress,sessionRange,showSession,onVerseLongPress,onBlankLongPress,onTap}:Props){
  useEffect(()=>{if(!isZipSource(mode))return;for(const neighbor of [page-1,page+1])if(neighbor>=1&&neighbor<=604)for(let line=0;line<15;line++)Image.prefetch(quranLineUri(neighbor,line)).catch(()=>{});},[mode,page]);
  const [plainPositions,setPlainPositions]=useState<Record<number,{y:number;height:number}>>({});
  const pageView=useRef<View>(null),pendingTap=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>()=>{if(pendingTap.current)clearTimeout(pendingTap.current);},[page]);
  const selectAfterTap=(work:()=>void)=>{if(pendingTap.current)clearTimeout(pendingTap.current);pendingTap.current=setTimeout(()=>{pendingTap.current=null;if(allowTap())work();},300);};
  const colorPage=mode==='tajweedPages';
  const zipped=isZipSource(mode)?zipPageData(mode,page):null;
  const [sourceWidth,sourceHeight]=zipped?zipped.dimensions:colorPage?(tajweedDimensionsRaw as Record<string,number[]>)[String(page)]:[1920,3106];
  const rows=zipped?.rows??(colorPage?tajweedBoundsRaw as Record<string,number[][]>:bounds)[String(page)]??[];
  const range=isZipSource(mode)?zipPageRange(mode,page):pageRange(page);
  const ids=Array.from({length:range.end-range.start+1},(_,index)=>range.start+index);
  const verseSelected=(id:number)=>id===playingVerseId;
  if(language==='fr'||mode==='tajweed')return <View style={{width,minHeight:height,backgroundColor:colors.soft,borderRadius:9,padding:12}}>
    {studyBanner?<View style={{marginBottom:8}}>{studyBanner}</View>:<Label style={{textAlign:'center',color:colors.gold,fontSize:13,marginBottom:12}}>{language==='fr'?'Traduction française du sens des versets':`Lecture simplifiée · page ${page}`}</Label>}
    {ids.map(id=>{const verse=verseAt(id),translation=frenchVerse(id),spans=language==='ar'?tajweedSpans(id):[];const difficult=difficultyIds.includes(id);return <Pressable key={id} onLayout={event=>{const {y,height}=event.nativeEvent.layout;setPlainPositions(old=>old[id]?.y===y&&old[id]?.height===height?old:{...old,[id]:{y,height}});}} onLongPress={()=>onVerseLongPress(id)} delayLongPress={450} onPress={()=>{if(!allowTap())return;if(onVersePress)selectAfterTap(()=>onVersePress(id));else onTap();}} style={{padding:10,marginBottom:8,borderRadius:12,backgroundColor:difficult?'#FCE8E8':bookmarkIds.includes(id)?colors.selected:verseSelected(id)?colors.selected:colors.paper,borderWidth:difficult?1:0,borderColor:difficult?'#D97878':colors.green2}}>
      <Label style={{fontSize:12,color:colors.gold,marginBottom:5}}>{surahs[verse.surah-1].name} · verset {verse.ayah}</Label>
      {language==='fr'?<><Label style={{fontSize:16,lineHeight:25}}>{translation?.translation??'Traduction indisponible.'}</Label>{translation?.footnotes?<Label style={{fontSize:12,color:colors.muted,marginTop:5}}>{translation.footnotes}</Label>:null}</>:
        <Text style={{fontSize:Math.min(34,Math.max(25,width*.078))*textScale,lineHeight:Math.min(62,Math.max(48,width*.145))*textScale,textAlign:'right',writingDirection:'rtl',color:colors.text}}>{spans.map((span,index)=><Text key={index} style={{color:span.rule?tajweedColor(span.rule):colors.text}}>{span.text}</Text>)} <Text style={{color:colors.gold}}>۞</Text></Text>}
    </Pressable>;})}
    {showSession&&(()=>{const active=ids.filter(id=>id>=sessionRange.start&&id<=sessionRange.end&&plainPositions[id]);if(!active.length)return null;const first=plainPositions[active[0]],last=plainPositions[active.at(-1)!];return <View pointerEvents="none" style={{position:'absolute',inset:0}}><View style={{position:'absolute',left:10,top:first.y+10,height:last.y+last.height-first.y-10,width:1,backgroundColor:sessionColor,opacity:.35}}/>{active.map(id=><View key={id} style={{position:'absolute',left:0,top:plainPositions[id].y+10,width:20,height:20,borderRadius:10,borderWidth:1,borderColor:sessionColor,backgroundColor:id<=sessionThrough?sessionColor:colors.paper,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:10,color:id<=sessionThrough?'white':sessionColor}}>{verseAt(id).ayah}</Text></View>)}</View>;})()}
    {language==='fr'?<Label style={{fontSize:11,color:colors.muted,marginTop:8}}>Traduction du sens : Rachid Maach · QuranEnc</Label>:<Label style={{fontSize:11,color:colors.muted,marginTop:8}}>Tajweed : cpfair, CC BY 4.0 · texte Hafs Tanzil 2017</Label>}
  </View>;
  const padding=zipped?0:2;
  const hitVerse=(event:GestureResponderEvent,callback:(id:number|null)=>void)=>{if(mapImagePoint){mapImagePoint(event,(x,y)=>callback(verseAtImagePoint(rows,x-padding,y-padding,width-padding*2,height-padding*2,sourceWidth,sourceHeight)));return;}const {pageX,pageY}=event.nativeEvent;pageView.current?.measureInWindow((left,top)=>callback(verseAtImagePoint(rows,pageX-left-padding,pageY-top-padding,width-padding*2,height-padding*2,sourceWidth,sourceHeight)));};
  return <View style={{width,height}}><Pressable ref={pageView} onPress={event=>{if(!allowTap())return;if(onVersePress)hitVerse(event,id=>{if(id!==null)selectAfterTap(()=>onVersePress(id));});else onTap();}} onLongPress={event=>hitVerse(event,id=>{if(id===null)onBlankLongPress();else onVerseLongPress(id);})} delayLongPress={450} style={{width,height,backgroundColor:'white',borderWidth:zipped?0:2,borderColor:colors.beige,borderRadius:zipped?0:9,overflow:'hidden',shadowColor:'#000',shadowOpacity:0.12,shadowRadius:10}}>
    {mode==='coran_1441'?<View accessibilityLabel={`Mushaf · page ${page}`} pointerEvents="none" style={{width,height}}>
      {Array.from({length:15},(_,line)=>({uri:quranLineUri(page,line)})).map((asset,line)=><Image key={line} source={asset} style={{position:'absolute',left:0,top:(height-width*232/1440)/14*line,width,height:width*232/1440}} resizeMode="contain" />)}
      {((madaniMarkers as Record<string,number[][]>)[page]??[]).map(([surah,ayah,line,x,y])=>{const diameter=width*.05;return <View key={`${surah}:${ayah}`} style={{position:'absolute',left:x*width-diameter/2,top:(height-width*232/1440)/14*line+y*width*232/1440-diameter/2,width:diameter,height:diameter,borderRadius:diameter/2,borderWidth:width*.003,borderColor:'#047857',backgroundColor:'#ECFDF5',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:width*.025,color:'#047857',lineHeight:diameter*.8,includeFontPadding:false}}>{String(ayah).replace(/\d/g,n=>'٠١٢٣٤٥٦٧٨٩'[Number(n)])}</Text></View>;})}
    </View>:<Image accessibilityLabel={`Mushaf · page ${page}`} source={colorPage?mushafTajweedImages[page]:mushafImages[page]} style={{width:width-padding*2,height:height-padding*2}} resizeMode="contain" />}
    {rows.filter(row=>{const id=verseId(row[0],row[1]);return id!==null&&(verseSelected(id)||difficultyIds.includes(id)||bookmarkIds.includes(id));}).map((row,index)=>{const id=verseId(row[0],row[1])!,active=id===playingVerseId,difficult=difficultyIds.includes(id);return <View key={index} pointerEvents="none" style={{position:'absolute',left:padding+row[3]/sourceWidth*(width-padding*2),top:padding+row[5]/sourceHeight*(height-padding*2),width:(row[4]-row[3])/sourceWidth*(width-padding*2),height:(row[6]-row[5])/sourceHeight*(height-padding*2),backgroundColor:difficult?'#E85B5B':bookmarkIds.includes(id)?colors.green2:active?colors.selected:colors.gold,opacity:bookmarkIds.includes(id)?0.18:difficult?0.18:active?0.42:0.11,borderWidth:0,borderColor:colors.green,borderRadius:4}} />;})}
    {bookmarkIds.map(id=>{const row=rows.find(r=>verseId(r[0],r[1])===id);return row?<View key={`bookmark-${id}`} pointerEvents="none" accessibilityLabel={`Marque-page verset ${verseAt(id).ayah}`} style={{position:'absolute',right:padding,top:padding+row[5]/sourceHeight*(height-padding*2)}}><Icon name="bookmark" size={14} color={colors.green}/></View>:null;})}
  </Pressable>    {showSession&&(()=>{const entries=rows.flatMap(row=>{const id=verseId(row[0],row[1]);return id===null?[]:[{id,ayah:row[1],line:row[2],x:row[3]/sourceWidth,y:row[5]/sourceHeight,width:(row[4]-row[3])/sourceWidth,height:(row[6]-row[5])/sourceHeight}];});const groups=marginAnnotations(entries,sessionRange.start,sessionRange.end,sessionThrough);if(!groups.length)return null;const edge=Math.min(...entries.map(r=>r.x))*(width-padding*2)+padding,diameter=Math.min(24,Math.max(8,edge+marginGutter-4)),left=edge-diameter-2;return <View pointerEvents="none" style={{position:'absolute',inset:0}}><View style={{position:'absolute',left:left+diameter/2,top:padding+groups[0].y*(height-padding*2),height:(groups[groups.length-1].bottom-groups[0].y)*(height-padding*2),width:1,backgroundColor:sessionColor,opacity:0.35}}/>{groups.map((group,index)=>{const done=group.items.every(item=>item.done);return <View key={index} accessibilityLabel={group.items.map(item=>`Verset ${item.ayah}${item.done?' validé':''}`).join(', ')} style={{position:'absolute',left,top:padding+(group.y+group.height*.35)*(height-padding*2)-diameter/2,width:diameter,minHeight:diameter,borderRadius:diameter/2,borderWidth:1,borderColor:sessionColor,backgroundColor:done?sessionColor:'white',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:group.items.length>1?8:Math.min(11,diameter*.55),color:done?'white':sessionColor,textAlign:'center'}}>{group.items.map(item=>item.ayah).join('·')}</Text></View>;})}</View>;})()}
</View>;
}
