import {StudyResumeCard} from './ui/StudySession';
import {resumeStudyTask} from './core/studyProgress';
import React,{useState} from 'react';
import {Pressable,ScrollView,View} from 'react-native';
import {AppState,memorizedIds,todayLocal} from './core/program';
import {reference} from './core/quran';
import {ReviewTask,reviewPlan,reviewQuantity,reviewWeight,reviewRhythm,setReviewCycle,setReviewQuantity} from './core/review';
import {Button,Card,colors,Label,Title} from './ui/theme';
import {Icon,IconName,ProgressTrack,premiumShadow} from './ui/Premium';

export function ReviewDashboard({state,update,onClose,onStart,onTask,onStatistics,onRecitations}:{state:AppState;update:(s:AppState)=>void;onClose:()=>void;onStart:()=>void;onTask:(task:ReviewTask)=>void;onStatistics:()=>void;onRecitations:()=>void}){
 const plan=reviewPlan(state),at=todayLocal(),cycle=plan.cycle;
 const [allConsolidations,setAllConsolidations]=useState(false),[allPriorities,setAllPriorities]=useState(false);
 const weight=(ids:number[])=>ids.reduce((n,id)=>n+reviewWeight(id),0);
 const completedSet=new Set(cycle?.completed??[]);
 const completed=cycle?weight(cycle.completed)/Math.max(.000001,weight(cycle.corpus)):0;
 const [cyclePicker,setCyclePicker]=useState(false);
 const changeCycle=()=>setCyclePicker(!cyclePicker);
 const heading=(icon:IconName,title:string,action?:React.ReactNode)=><View style={{flexDirection:'row',alignItems:'center',gap:8,marginBottom:12}}><Icon name={icon} color={colors.green} size={22}/><Label style={{flex:1,fontSize:17,fontWeight:'800'}}>{title}</Label>{action}</View>;
 const summary:[IconName,string,ReviewTask[]][]=[['book-open-variant','Cycle du jour',plan.habitual],['sprout','Consolidation',plan.recent],['refresh','À retravailler',plan.priority]];
 return <ScrollView contentContainerStyle={{padding:16,paddingBottom:30}}><Pressable accessibilityLabel="Retour" onPress={onClose} style={{minHeight:44,justifyContent:'center'}}><Icon name="chevron-left" color={colors.green}/></Pressable><Title>Mes révisions</Title><Label style={{color:colors.muted,fontSize:13,lineHeight:20,marginBottom:16}}>Un programme fondé sur les versets réellement mémorisés.</Label>
 {Object.values(state.studyProgress??{}).filter(r=>r.mode==='revision'&&r.status==='partial').map(record=><StudyResumeCard key={record.id} record={record} onResume={()=>onTask(resumeStudyTask(record))}/>)}
 <Card style={{backgroundColor:colors.soft,...premiumShadow}}>{heading('calendar-check-outline','Ma révision du jour')}<View style={{flexDirection:'row',marginBottom:16}}>{summary.map(([icon,label,tasks],i)=><View key={label} style={{flex:1,alignItems:'center',paddingHorizontal:3,borderRightWidth:i<2?1:0,borderColor:colors.line}}><Icon name={icon} color={colors.green}/><Label style={{fontSize:11,textAlign:'center',marginTop:6}}>{label}</Label><Label style={{fontSize:14,fontWeight:'800',textAlign:'center',marginTop:6}}>{reviewQuantity(tasks)}</Label><Label numberOfLines={2} style={{fontSize:10,textAlign:'center',color:colors.muted,marginTop:6}}>{tasks[0]?`${reference(tasks[0])}${tasks.length>1?'…':''}`:'Rien à revoir'}</Label></View>)}</View><Button disabled={!plan.session.length} onPress={onStart}>Commencer ma révision</Button><Label style={{fontSize:12,lineHeight:18,textAlign:'center',color:colors.muted,marginTop:8}}>{plan.session.length?'La séance du jour regroupe automatiquement ton cycle, tes consolidations et tes versets prioritaires.':'Ta révision du jour est terminée, ou aucune échéance n’est prévue aujourd’hui.'}</Label></Card>
 <Card>{heading('chart-bar','Mon cycle de révision',<Pressable accessibilityRole="button" onPress={changeCycle} accessibilityLabel="Modifier la durée du cycle" style={{minHeight:44,minWidth:64,alignItems:'center',justifyContent:'center'}}><Label style={{fontSize:12,color:colors.green}}>Modifier</Label></Pressable>)}{cyclePicker&&<View style={{flexDirection:'row',gap:4,marginBottom:8}}>{([7,14,21,30] as const).map(days=><View key={days} style={{flex:1}}><Button small secondary={cycle?.lengthDays!==days} onPress={()=>{update(setReviewCycle(state,days));setCyclePicker(false);}}>{days} jours</Button></View>)}</View>}{cyclePicker&&<View style={{gap:6,marginBottom:12}}>{(['nisf','hizb','juz','juz2'] as const).map((q,i)=><Button key={q} small secondary onPress={()=>{update(setReviewQuantity(state,q));setCyclePicker(false);}}>{['1 Nisf / jour','1 Hizb / jour','1 Juz / jour','2 Juz / jour'][i]}</Button>)}</View>}<View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:10}}><Label>{state.reviewSettings?.mode==='quantity'?{nisf:'1 Nisf / jour',hizb:'1 Hizb / jour',juz:'1 Juz / jour',juz2:'2 Juz / jour'}[state.reviewSettings.dailyQuantity??'hizb']:`Cycle de ${cycle?.lengthDays??7} jours`}</Label><Label>Jour {plan.cycleDay} / {cycle?.lengthDays??7}</Label></View><ProgressTrack value={completed}/><Label style={{textAlign:'right',fontSize:12,color:colors.green,marginTop:6}}>{Math.round(completed*100)} % réellement révisés</Label><Label style={{fontSize:11,color:colors.muted,lineHeight:18,marginTop:8}}>{memorizedIds(state).length} versets mémorisés · {plan.completeJuz} Juz’ · {plan.completeRub} Rubu’ · {plan.completeNisf} Nisf</Label><View style={{flexDirection:'row',justifyContent:'space-between',marginVertical:14,gap:8}}>{[[reviewQuantity(cycle?.corpus??[]),'à revoir'],[reviewQuantity(cycle?.completed??[]),'révisés'],[reviewQuantity(cycle?.corpus.filter(id=>!completedSet.has(id))??[]),'restants']].map(([value,label])=><View key={label} style={{flex:1}}><Label style={{fontWeight:'700',fontSize:13}}>{value}</Label><Label style={{color:colors.muted,fontSize:11}}>{label}</Label></View>)}</View><View style={{padding:12,borderRadius:16,backgroundColor:colors.soft}}><Label style={{fontSize:12,color:colors.muted}}>Rythme du cycle · moyenne</Label><Label style={{fontWeight:'800',marginTop:4}}>{cycle?.corpus.length?reviewRhythm(cycle):'Aucun verset dans ce cycle'}</Label></View><Label style={{fontSize:12,lineHeight:18,color:colors.muted,marginTop:10}}>Tout le corpus du cycle sera proposé. Une journée manquée reste à faire et peut décaler la fin du cycle.</Label></Card>
 <Card>{heading('sprout','Nouveaux versets à consolider')}<Label style={{fontSize:12,color:colors.muted,lineHeight:18,marginBottom:10}}>Les nouveaux versets appris sont revus à J+1, J+3 puis J+7, avant d’intégrer le prochain cycle.</Label>{!plan.consolidations.length&&<Label style={{color:colors.muted}}>Aucun nouveau verset à consolider.</Label>}{(allConsolidations?plan.consolidations:plan.consolidations.slice(0,5)).map(row=><Pressable accessibilityRole="button" accessibilityLabel={`Consolider ${reference(row)}`} onPress={()=>onTask({...row,id:`consolidation-${row.start}-${row.end}`,category:'recent',label:'Consolidation'})} key={`${row.start}-${row.end}`} style={{borderWidth:1,borderColor:colors.line,borderRadius:16,padding:12,marginTop:8}}><Label style={{fontWeight:'800'}}>{reference(row)}</Label><Label style={{fontSize:12,color:colors.muted,marginTop:4}}>{reviewQuantity([row])} · appris le {new Date(`${row.learnedAt}T12:00:00`).toLocaleDateString('fr-FR')}</Label><View style={{flexDirection:'row',marginTop:12}}>{row.steps.map(step=><View key={step.offset} style={{flex:1,alignItems:'center',borderTopWidth:2,borderColor:step.completed?colors.green:colors.line,paddingTop:8}}><Icon name={step.completed?'check-circle':step.due<=at?'clock-outline':'circle-outline'} size={20} color={step.completed||step.due<=at?colors.green:colors.muted}/><Label style={{fontWeight:'700',fontSize:12,marginTop:4}}>J+{step.offset}</Label><Label style={{fontSize:10,color:colors.muted,textAlign:'center'}}>{step.completed?'Consolidé':step.due===at?'Aujourd’hui':step.due<at?'À rattraper':'À venir'}</Label><Label style={{fontSize:10,color:colors.muted}}>{new Date(`${step.completed??step.due}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</Label></View>)}</View></Pressable>)}{plan.consolidations.length>5&&<Button small secondary onPress={()=>setAllConsolidations(!allConsolidations)}>{allConsolidations?'Réduire':'Voir toutes les consolidations'}</Button>}</Card>
 <Card>{heading('refresh','À retravailler')}<Label style={{color:colors.green,fontWeight:'700',marginBottom:8}}>{reviewQuantity(plan.priority)} à retravailler aujourd’hui</Label>{!plan.rework.length&&<Label style={{color:colors.muted,fontSize:12}}>Aucun verset prioritaire prévu aujourd’hui.</Label>}{(allPriorities?plan.rework:plan.rework.slice(0,5)).map(task=><Pressable key={task.id} accessibilityRole="button" onPress={()=>onTask(task)} style={{minHeight:58,paddingVertical:10,borderBottomWidth:1,borderColor:colors.line}}><Label style={{fontWeight:'700'}}>{reference(task)} ›</Label><Label style={{fontSize:12,color:colors.muted,marginTop:4}}>{reviewQuantity([task])} · marqué lors d’une révision précédente</Label></Pressable>)}{plan.rework.length>5&&<Button small secondary onPress={()=>setAllPriorities(!allPriorities)}>{allPriorities?'Réduire':'Voir tous les versets prioritaires'}</Button>}</Card>
 <Card>{heading('chart-timeline-variant','Mon suivi')}<Label style={{fontSize:12,lineHeight:20,color:colors.muted}}>{memorizedIds(state).length} versets mémorisés · {plan.completeJuz} Juz’ · {plan.completeRub} Rubu’ · {plan.completeNisf} Nisf</Label><Label style={{marginTop:8}}>{state.reviewHistory?.length??0} révisions effectuées</Label><Button secondary onPress={onStatistics}>Voir mes statistiques</Button><Button small secondary onPress={onRecitations}>Mes récitations</Button></Card></ScrollView>;
}